// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Inventory.Data
{
    public partial class V2Outasn
    {
        public string Cticketcode { get; set; }
        public decimal Itype { get; set; }
        public string Typename { get; set; }
        public string Cstatus { get; set; }
        public string Cstatusname { get; set; }
        public string Reasoncode { get; set; }
        public string Ccreateownercode { get; set; }
        public string Ccreateownername { get; set; }
        public DateTime Dcreatetime { get; set; }
    }
}