// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Inventory.Data
{
    public partial class VOutasnlist
    {
        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditpersoncode { get; set; }
        public DateTime? Dauditdate { get; set; }
        public string Cticketcode { get; set; }
        public string Cerpcode { get; set; }
        public string Cstatus { get; set; }
        public string FlagName { get; set; }
        public decimal Itype { get; set; }
        public string Typename { get; set; }
        public string Cdefine2 { get; set; }
        public decimal IsMerge { get; set; }
        public DateTime? StartDates { get; set; }
        public string Shifts { get; set; }
        public string IsMergename { get; set; }
        public int? IsSpecialWipIssue { get; set; }
        public string SpecialOut { get; set; }
        public string Smttype { get; set; }
        public int? IsCj { get; set; }
        public string Cstatusname { get; set; }
        public string Smttypeint { get; set; }
        public string Cso { get; set; }
        public string Worktype { get; set; }
    }
}