// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Inventory.Data
{
    public partial class V2ViewDef
    {
        public string ViewInfo { get; set; }
    }
}