// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Inventory.Data
{
    public partial class VStockCurrent
    {
        public string Id { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cwarehouse { get; set; }
        public string Cdatecode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal Iqty { get; set; }
        public decimal Ioccupyqty { get; set; }
        public decimal LockNum { get; set; }
    }
}