// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class AllocateDMerge
    {
        public string Ids { get; set; }
        public string AllocateId { get; set; }
        public string AllocateDIds { get; set; }
        public string Cerpcode { get; set; }
        public string Cstatus { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
        public decimal? Toallocount { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Ctopositioncode { get; set; }
        public string Ctoposition { get; set; }
        public string AlloType { get; set; }
        public decimal? Sptype { get; set; }
        public decimal? IsScan { get; set; }
        public decimal? PartBond { get; set; }
        public string Define1 { get; set; }
        public string Define2 { get; set; }
        public string Define3 { get; set; }

        public virtual Allocate Allocate { get; set; }
    }
}