// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class AllocateDBn
    {
        public string Ids { get; set; }
        public string Snids { get; set; }
        public string Bncode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Qty { get; set; }
        public string Cstatus { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateuser { get; set; }
        public string Cdefined1 { get; set; }
        public string Cdefined2 { get; set; }
        public string Memo { get; set; }
    }
}