// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class AllocateHis
    {
        public AllocateHis()
        {
            AllocateDHis = new HashSet<AllocateDHis>();
        }

        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditperson { get; set; }
        public DateTime? Daudittime { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Cerpcode { get; set; }
        public string Cmemo { get; set; }
        public DateTime Dindate { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Deleteuser { get; set; }
        public DateTime? Deletetime { get; set; }

        public virtual ICollection<AllocateDHis> AllocateDHis { get; set; }
    }
}