// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BarCartonDHis
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cinbarid { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal? Qty { get; set; }
        public DateTime Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastmodifytime { get; set; }
        public string Lastmodifyowner { get; set; }
    }
}