// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BarRepack
    {
        public string Id { get; set; }
        public string RepackNo { get; set; }
        public decimal Type { get; set; }
        public string Repackid { get; set; }
        public string RepackidHis { get; set; }
        public DateTime RepackDate { get; set; }
        public string RepackOwner { get; set; }
        public DateTime Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastmodifytime { get; set; }
        public string Lastmodifyowner { get; set; }
    }
}