// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BaseArea
    {
        public string Id { get; set; }
        public string AreaName { get; set; }
        public string Memo { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastvpdtime { get; set; }
        public string Lastvpdowner { get; set; }
        public string HandoverCargo { get; set; }
        public string HandoverCargoName { get; set; }
        public string Flag { get; set; }
        public string IsControl { get; set; }
        /// <summary>
        /// 是否暂存区域  0：不是  1：是
        /// </summary>
        public string IsTemporaryArea { get; set; }
    }
}