// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BaseSendemailpelon
    {
        public string Id { get; set; }
        /// <summary>
        /// 发件人邮件地址
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 发件人邮件密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 端口
        /// </summary>
        public string Prot { get; set; }
        public string Host { get; set; }
        /// <summary>
        /// 是否启用 0不启用，1启用
        /// </summary>
        public int? Enablessl { get; set; }
    }
}