// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BasePartTemp
    {
        public string Cspecifications { get; set; }
        public string Inw { get; set; }
        public string Icw { get; set; }
        public string Cunits { get; set; }
        public string Ineedcheck { get; set; }
        public string Cinrule { get; set; }
        public string Coutrule { get; set; }
        public string Ilength { get; set; }
        public string Iwidth { get; set; }
        public string Iheight { get; set; }
        public string Cusetype { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Ddefine3 { get; set; }
        public string Ddefine4 { get; set; }
        public string Idefine5 { get; set; }
        public string Cmemo { get; set; }
        public string Dexpiredate { get; set; }
        public string Calias { get; set; }
        public string Cerpcode { get; set; }
        public string Csafeqty { get; set; }
        public string Ineedwarn { get; set; }
        public string Cstatus { get; set; }
        public string Cpartnumber { get; set; }
        public string Cpartname { get; set; }
        public string Ctype { get; set; }
        public string Cdefaultware { get; set; }
        public string Cdefaultcargo { get; set; }
        public string Cversion { get; set; }
        public string Cbarrule { get; set; }
        public string Cdefaultvendor { get; set; }
        public string Cvolume { get; set; }
        public string Createtime { get; set; }
        public string Createowner { get; set; }
        public string Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public string Bonded { get; set; }
        public string Mtype { get; set; }
        public string ExpDays { get; set; }
        public string Volumeunits { get; set; }
        public string Referunit { get; set; }
        public string Baseunit { get; set; }
        public string Companyno { get; set; }
        public string Strongholdno { get; set; }
        public string Organizationno { get; set; }
        public string Id { get; set; }
        public decimal? Flag { get; set; }
        public string Needserial { get; set; }
    }
}