// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BaseOperatorAreaBak
    {
        public string Caccountid { get; set; }
        public string Ccargoid { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Ccreateowner { get; set; }
        public string Id { get; set; }
    }
}