// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BaseJobRunTime
    {
        public string Id { get; set; }
        public string Jobname { get; set; }
        public string Jobdesc { get; set; }
        public DateTime? Runtime { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Cdefine3 { get; set; }
        public string Remark { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
    }
}