// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BaseFileuplod
    {
        public string Id { get; set; }
        public string Filename { get; set; }
        public string Newfilename { get; set; }
        public string Suffix { get; set; }
        public string Filesize { get; set; }
        public string Path { get; set; }
        public string Po { get; set; }
        public string Prantno { get; set; }
        public string Lusn { get; set; }
        public string Luno { get; set; }
        public string Sn { get; set; }
    }
}