// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class BaseCraneconfigDetialScan
    {
        /// <summary>
        /// base_craneconfig_detial主键ID
        /// </summary>
        public string Ids { get; set; }
        public string Id { get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
        public string Siteid { get; set; }
        /// <summary>
        /// 扫描器ID
        /// </summary>
        public string Scanid { get; set; }
        /// <summary>
        /// 扫描器名称
        /// </summary>
        public string Scanname { get; set; }
        /// <summary>
        /// 扫描器IP
        /// </summary>
        public string Scanip { get; set; }
        public string Flag { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public string Updateuser { get; set; }
        public DateTime? Updatetime { get; set; }
        public string ScanType { get; set; }
        public string Discontinueuser { get; set; }
        public DateTime? Discontinuetime { get; set; }
        public string Serverscanip { get; set; }
        public string Scanportno { get; set; }
    }
}