// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class CmdbyPalletCode
    {
        public string Id { get; set; }
        /// <summary>
        /// 站点类型 0，立库 1，RGV 2，提升机 3，AGV
        /// </summary>
        public string Stntype { get; set; }
        /// <summary>
        /// RGV站点：一楼，101~109；2楼，201~210 提升机：1~4 立库：一号线，101~104；二号线，201~204；三号线，301~304 AGV：参考结构图。二楼，D01~D81；四楼以F开头
        /// </summary>
        public string Stnno { get; set; }
        /// <summary>
        /// 栈板编号
        /// </summary>
        public string PalletCode { get; set; }
        /// <summary>
        /// 返回码 0，成功 1，失败
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// 返回信息，&quot;成功&quot;、&quot;失败&quot;
        /// </summary>
        public string Message { get; set; }
        /// <summary>
        /// 自定义返回
        /// </summary>
        public string Data { get; set; }
    }
}