// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class CmdMstScan
    {
        public string Id { get; set; }
        /// <summary>
        /// 台车线路
        /// </summary>
        public string Lineid { get; set; }
        /// <summary>
        /// 台车站点编号
        /// </summary>
        public string Siteid { get; set; }
        /// <summary>
        /// 栈板号
        /// </summary>
        public string Palletcode { get; set; }
        /// <summary>
        /// 扫描时间
        /// </summary>
        public DateTime Scantime { get; set; }
    }
}