// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class Current001
    {
        public string Cpositioncode { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Iqty { get; set; }
    }
}