// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class DataInputTemp
    {
        public string Bcid { get; set; }
        public string Areaname { get; set; }
        public string Bcidname { get; set; }
        public string Item { get; set; }
        public string Type { get; set; }
    }
}