// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class HandleLog
    {
        public string Id { get; set; }
        public string Userno { get; set; }
        public DateTime Opttime { get; set; }
        public string HandleType { get; set; }
        public string HandleTable { get; set; }
        public string RecordId { get; set; }
        public string Reservefield1 { get; set; }
        public string Reservefield2 { get; set; }
        public string Reservefield3 { get; set; }
        public string Reservefield4 { get; set; }
        public string Reservefield5 { get; set; }
        public string Reservefield6 { get; set; }
        public string Reservefield7 { get; set; }
        public string Reservefield8 { get; set; }
    }
}