// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class HdSqlmap
    {
        public string SqlOp { get; set; }
        public string SqlName { get; set; }
        public string SqlContent { get; set; }
        public string SqlDesc { get; set; }
        public string SqlStatus { get; set; }
        public string SqlOwner { get; set; }
        public DateTime? SqlDate { get; set; }
        public string SqlObligate1 { get; set; }
        public string SqlObligate2 { get; set; }
        public string SqlObligate3 { get; set; }
    }
}