// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class InasnchangeD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Oldnum { get; set; }
        public decimal? Nownum { get; set; }
        public string CreateOwner { get; set; }
        public DateTime? CreateTime { get; set; }
        public string LastUpdOwner { get; set; }
        public DateTime? LastUpdTime { get; set; }
        public string Cmemo { get; set; }
        public string Cerpcodeline { get; set; }
        public string AsnDIds { get; set; }

        public virtual Inasnchange IdNavigation { get; set; }
    }
}