// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class InasnDIstockSplit
    {
        public string Id { get; set; }
        public string AsnId { get; set; }
        public string AsnDIds { get; set; }
        public string Cinvcode { get; set; }
        public string Flag { get; set; }
        public decimal? Oldqty { get; set; }
        public decimal? Cjqty { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
    }
}