// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class InasnDAppBak
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cbatch { get; set; }
        public string Cmemo { get; set; }
        public string Cerpcodeline { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Cpo { get; set; }
        public decimal? Ipoline { get; set; }
        public string Erpcodelinenum { get; set; }
        public string PoNumbername { get; set; }
        public string PoLinenumbername { get; set; }
        public decimal? Manual { get; set; }
        public decimal? Datecode { get; set; }
        public string InasnIaDIds { get; set; }
        public int? LineId { get; set; }
        public string Unit { get; set; }
        public string DfWhscode { get; set; }
        public string DfShscode { get; set; }
        public string Reasoncode { get; set; }
    }
}