// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class InbillDBn
    {
        public string Id { get; set; }
        public string Snids { get; set; }
        public string BnCode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Quantity { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastvpdtime { get; set; }
        public string Lastvpdowner { get; set; }
        public string Worktype { get; set; }
        public string Istransed { get; set; }
        public DateTime? Transedtime { get; set; }
        public string UnionId { get; set; }
        public string ScanIds { get; set; }
        public decimal? Bntype { get; set; }
        public decimal? LineQty { get; set; }
        public string Furnaceno { get; set; }
        public string BnCode20 { get; set; }
    }
}