// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class Inbill
    {
        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Cauditperson { get; set; }
        public DateTime? Daudittime { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Casnid { get; set; }
        public DateTime Dindate { get; set; }
        public string Cmemo { get; set; }
        public string Cerpcode { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public decimal Itype { get; set; }
        public string Cvendercode { get; set; }
        public string Cvender { get; set; }
        public DateTime? Debittime { get; set; }
        public string Debitowner { get; set; }
        public string Palletcode { get; set; }
        public string Creatertype { get; set; }
        public string Worktype { get; set; }
        public int? Operationtype { get; set; }
        public string IsTemporary { get; set; }
    }
}