// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class InpoD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Poline { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
        public string Unit { get; set; }
        public decimal? Price { get; set; }
        public decimal? Status { get; set; }
        public string Define1 { get; set; }
        public string Define2 { get; set; }
        public string Define3 { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public decimal? Qc { get; set; }

        public virtual Inpo IdNavigation { get; set; }
    }
}