// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class LogSyserrorAppBak
    {
        public DateTime Opttime { get; set; }
        public string Id { get; set; }
        public string SovrceNo { get; set; }
        public string Errormsg { get; set; }
        public decimal Type { get; set; }
        public DateTime Createdate { get; set; }
    }
}