// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class OutasnD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal Iquantity { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cbatch { get; set; }
        public string Cerpcodeline { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Cso { get; set; }
        public decimal? Isoline { get; set; }
        public string Site { get; set; }
        public decimal? IsSmt { get; set; }
        public decimal? Manual { get; set; }
        public int? Lineid { get; set; }
        /// <summary>
        /// 合并数量
        /// </summary>
        public decimal? Mergeqty { get; set; }
        /// <summary>
        /// 单位名称
        /// </summary>
        public string Unit { get; set; }
        /// <summary>
        /// 预设仓库
        /// </summary>
        public string DfWhscode { get; set; }
        /// <summary>
        /// 预设储位
        /// </summary>
        public string DfShscode { get; set; }
        public string Wo { get; set; }
    }
}