// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class Outasnnotuseouttype
    {
        public string Erpcode { get; set; }
        public string Typename { get; set; }
    }
}