// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class OutasnBuild
    {
        public string MoName { get; set; }
        public string ItemId { get; set; }
        public decimal? TotalCount { get; set; }
        public string MoId { get; set; }
        public string SmtFalg { get; set; }
        public string EndItem { get; set; }
        public string ItemName { get; set; }
        public string Side { get; set; }
        public decimal? Num { get; set; }
        public string ClassCode { get; set; }
        public string SemiManufactures { get; set; }
        public string Oflag { get; set; }
        public string Id { get; set; }
    }
}