// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class OutGroupHis
    {
        public string LogId { get; set; }
        public string Id { get; set; }
        public string GroupName { get; set; }
        public string Remark { get; set; }
        public string CreateOwner { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastUpdOwner { get; set; }
        public DateTime? LastUpdDate { get; set; }
        public decimal? Cstatus { get; set; }
    }
}