// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class OutHandoverHis
    {
        public string Id { get; set; }
        public string OutbillDId { get; set; }
        public decimal? Qty { get; set; }
        public string Createowner { get; set; }
        public DateTime Createtime { get; set; }
        public string Deleteuser { get; set; }
        public DateTime? Deletetime { get; set; }
    }
}