// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class OutHandoverCheck
    {
        public string Id { get; set; }
        public string Cerpcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iqty { get; set; }
        public decimal? QtyDemand { get; set; }
        public decimal? QtyOut { get; set; }
        public decimal? QtyHandover { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public decimal? Cstatus { get; set; }
        public string Sncode { get; set; }
    }
}