// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class OutTransportationplan
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 出运计划号
        /// </summary>
        public string Docno { get; set; }
        /// <summary>
        /// 客户地址
        /// </summary>
        public string Customeraddr { get; set; }
        /// <summary>
        /// 币种
        /// </summary>
        public string Currency { get; set; }
        /// <summary>
        /// 运输方式
        /// </summary>
        public string Transtype { get; set; }
        /// <summary>
        /// 箱号
        /// </summary>
        public string Palletcode { get; set; }
        /// <summary>
        /// 销售单号
        /// </summary>
        public string Cerpcode { get; set; }
        /// <summary>
        /// 销售单项次号
        /// </summary>
        public string Cerpcodeline { get; set; }
        /// <summary>
        /// 物料编码
        /// </summary>
        public string Cinvcode { get; set; }
        /// <summary>
        /// 物料名称
        /// </summary>
        public string Cinvname { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public decimal? Iquantity { get; set; }
        /// <summary>
        /// 客户订单号
        /// </summary>
        public string Customerno { get; set; }
        /// <summary>
        /// 客户编码
        /// </summary>
        public string Cvendercode { get; set; }
        /// <summary>
        /// 客户名称
        /// </summary>
        public string Cvender { get; set; }
        /// <summary>
        /// 要求交货日期
        /// </summary>
        public DateTime? Reqdeliverydate { get; set; }
        /// <summary>
        /// 计划提货日期
        /// </summary>
        public DateTime? Pladeliverydate { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Memo { get; set; }
        /// <summary>
        /// 修改标记(WMS抓取数据并处理成功后回写。0-未处理；1-已处理;2-已发料)
        /// </summary>
        public int? Updatemark { get; set; }
        /// <summary>
        /// 最后修改时间(WMS更新时间)
        /// </summary>
        public DateTime? Wmsupdatetime { get; set; }
        /// <summary>
        /// 最后修改时间(OA更新时间)
        /// </summary>
        public DateTime? Oaupdatetime { get; set; }
        /// <summary>
        /// 创建日期(LN系统上传数据日期)
        /// </summary>
        public DateTime? Createtime { get; set; }
        /// <summary>
        /// 自定义1
        /// </summary>
        public string Cdefine1 { get; set; }
        /// <summary>
        /// 自定义2
        /// </summary>
        public string Cdefine2 { get; set; }
        /// <summary>
        /// 自定义3
        /// </summary>
        public DateTime? Ddefine3 { get; set; }
        /// <summary>
        /// 自定义4
        /// </summary>
        public DateTime? Ddefine4 { get; set; }
        /// <summary>
        /// 自定义5
        /// </summary>
        public decimal? Idefine5 { get; set; }
        /// <summary>
        /// 出运单生成时间
        /// </summary>
        public DateTime? Producetime { get; set; }
        /// <summary>
        /// 是否确认（0：是，1：否）
        /// </summary>
        public int? Issign { get; set; }
        /// <summary>
        /// 确认人
        /// </summary>
        public string Singnowner { get; set; }
        /// <summary>
        /// 确认日期
        /// </summary>
        public DateTime? Singtime { get; set; }
        public int Sntype { get; set; }
        public int PackSntype { get; set; }
    }
}