// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class PdaVInAsnList
    {
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Inum { get; set; }
        public decimal Yjnum { get; set; }
        public decimal? Synum { get; set; }
        public string Cticketcode { get; set; }
    }
}