// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class PoGetCache
    {
        public string ReceiptNum { get; set; }
        public DateTime? GetDate { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cerpcodeline { get; set; }
        public string Cpo { get; set; }
        public decimal? Ipoline { get; set; }
        public string Erpcodelinenum { get; set; }
        public string PoNumbername { get; set; }
        public string PoLinenumbername { get; set; }
    }
}