// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class ProcFunReturnInfo
    {
        public string FunProcName { get; set; }
        public decimal Sequence { get; set; }
        public string InfoCode { get; set; }
        public string InfoResult { get; set; }
        public string InfoMsg { get; set; }
        public string Memo { get; set; }
    }
}