// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class R09WhY
    {
        public string L { get; set; }
        public int? Z { get; set; }
        public int? Y { get; set; }
        public int? CntX { get; set; }
        public int? MinX { get; set; }
        public int? MaxX { get; set; }
    }
}