// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class R09Wh
    {
        public int? L { get; set; }
        public int? Z { get; set; }
        public int? Y { get; set; }
        public int? X { get; set; }
        public string Cell { get; set; }
        public string Lineid { get; set; }
        public string Cz { get; set; }
        public string Cy { get; set; }
        public string Cx { get; set; }
        public string Cpositioncode { get; set; }
    }
}