// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class SnResetOperateInfo
    {
        public string Id { get; set; }
        /// <summary>
        /// 儲位
        /// </summary>
        public string Cpositioncode { get; set; }
        /// <summary>
        /// 料號
        /// </summary>
        public string Cinvcode { get; set; }
        /// <summary>
        /// 凍結人
        /// </summary>
        public string Lockuser { get; set; }
        /// <summary>
        /// 凍結時間
        /// </summary>
        public DateTime? Locktime { get; set; }
        /// <summary>
        /// 解凍人
        /// </summary>
        public string Unlockuser { get; set; }
        /// <summary>
        /// 解凍時間
        /// </summary>
        public DateTime? Unlocktime { get; set; }
        /// <summary>
        /// 入庫通知單號
        /// </summary>
        public string Inasncode { get; set; }
        /// <summary>
        /// 是否存在差異
        /// </summary>
        public int? IsDiff { get; set; }
        /// <summary>
        /// 凍結狀態 0凍結 1解凍
        /// </summary>
        public int? Cstatus { get; set; }
        /// <summary>
        /// 自定義1
        /// </summary>
        public string Cdefine1 { get; set; }
        /// <summary>
        /// 自定義2
        /// </summary>
        public string Cdefine2 { get; set; }
    }
}