// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class SsxSiteMonitor
    {
        public string Id { get; set; }
        public string Lineid { get; set; }
        public string Siteid { get; set; }
        public string Palletcode { get; set; }
        public string Plc { get; set; }
        public DateTime Monitortime { get; set; }
        public string Remark { get; set; }
    }
}