// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class StockCurrentBegin
    {
        public string Id { get; set; }
        public string Begindate { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Iqty { get; set; }
        public DateTime? Createtime { get; set; }
        public string Remark { get; set; }
    }
}