// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class StockCheckbill
    {
        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Cauditperson { get; set; }
        public DateTime? Daudittime { get; set; }
        public string Cticketcode { get; set; }
        /// <summary>
        /// 状态（0:未处理,1.審核中，2.盤點中(初盤)，3.已完成(初盤)，4.盤點中（複盤），5.已完成（複盤）) 6.盘点中
        /// </summary>
        public string Cstatus { get; set; }
        public string Cerpcode { get; set; }
        public string Cmemo { get; set; }
        public DateTime Dcheckdate { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Checktype { get; set; }
        public DateTime? Dcirclecheckbegindate { get; set; }
        public DateTime? Dcirclecheckenddate { get; set; }
        public string Ccheckname { get; set; }
        public decimal? MaxPartIum { get; set; }
        public decimal? Isadjust { get; set; }
        /// <summary>
        /// 盘点计划名称
        /// </summary>
        public string Planname { get; set; }
        /// <summary>
        /// 复盘标记 1:初盘中 2:初盘完成 3:复盘中 4:复盘完成
        /// </summary>
        public string Statusf { get; set; }
        public string Worktype { get; set; }
        public string Lineid { get; set; }
        public string IsLxcheck { get; set; }
    }
}