// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class StockOccupancyRelease
    {
        public string ItemId { get; set; }
        public string Storage { get; set; }
        public decimal? Totalnum { get; set; }
        public string Cticketcode { get; set; }
        public string Flag { get; set; }
        public string Id { get; set; }
        public string Billid { get; set; }
        public DateTime? Opttime { get; set; }
        public decimal? Type { get; set; }
        public string AsnId { get; set; }
    }
}