// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class StockSnErpunlock
    {
        public string Id { get; set; }
        public string Erpcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cpositionname { get; set; }
        public string Sncode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Iqty { get; set; }
        public decimal? Cstatus { get; set; }
        public decimal? Sntype { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public decimal? Assited { get; set; }
    }
}