// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class SysCountlog
    {
        public string Id { get; set; }
        public string Casetype { get; set; }
        public string Caseid { get; set; }
        public string Caseno { get; set; }
        public int? Countbefore { get; set; }
        public int? Countafter { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public DateTime? Updatetime { get; set; }
        public string Updateuser { get; set; }
    }
}