// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class SysLanguage
    {
        public string Id { get; set; }
        public decimal LangType { get; set; }
        public string Code { get; set; }
        public string Text { get; set; }
        public string Memo { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
    }
}