// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class SysParametergroup
    {
        public string Id { get; set; }
        public string FlagType { get; set; }
        public DateTime? Createtime { get; set; }
        public string Remark { get; set; }
        public string Createuser { get; set; }
    }
}