// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    /// <summary>
    /// 用户表
    /// </summary>
    public partial class SysUser
    {
        /// <summary>
        /// 用户主键
        /// </summary>
        public string FId { get; set; }
        /// <summary>
        /// 账户
        /// </summary>
        public string FAccount { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string FRealName { get; set; }
        /// <summary>
        /// 呢称
        /// </summary>
        public string FNickName { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string FHeadIcon { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public bool? FGender { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? FBirthday { get; set; }
        /// <summary>
        /// 手机
        /// </summary>
        public string FMobilePhone { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string FEmail { get; set; }
        /// <summary>
        /// 微信
        /// </summary>
        public string FWeChat { get; set; }
        /// <summary>
        /// 主管主键
        /// </summary>
        public string FManagerId { get; set; }
        /// <summary>
        /// 安全级别
        /// </summary>
        public int? FSecurityLevel { get; set; }
        /// <summary>
        /// 个性签名
        /// </summary>
        public string FSignature { get; set; }
        /// <summary>
        /// 组织主键
        /// </summary>
        public string FOrganizeId { get; set; }
        /// <summary>
        /// 部门主键
        /// </summary>
        public string FDepartmentId { get; set; }
        /// <summary>
        /// 角色主键
        /// </summary>
        public string FRoleId { get; set; }
        /// <summary>
        /// 岗位主键
        /// </summary>
        public string FDutyId { get; set; }
        /// <summary>
        /// 是否管理员
        /// </summary>
        public bool? FIsAdministrator { get; set; }
        /// <summary>
        /// 排序码
        /// </summary>
        public int? FSortCode { get; set; }
        /// <summary>
        /// 删除标志
        /// </summary>
        public bool? FDeleteMark { get; set; }
        /// <summary>
        /// 有效标志
        /// </summary>
        public bool? FEnabledMark { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string FDescription { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? FCreatorTime { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string FCreatorUserId { get; set; }
        /// <summary>
        /// 最后修改时间
        /// </summary>
        public DateTime? FLastModifyTime { get; set; }
        /// <summary>
        /// 最后修改用户
        /// </summary>
        public string FLastModifyUserId { get; set; }
        /// <summary>
        /// 删除时间
        /// </summary>
        public DateTime? FDeleteTime { get; set; }
        /// <summary>
        /// 删除用户
        /// </summary>
        public string FDeleteUserId { get; set; }
    }
}