// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempAreaPaetWarehouse
    {
        public string Id { get; set; }
        public string AreaName { get; set; }
        public string Cpartnumber { get; set; }
        public string Cpositioncode { get; set; }
        public string Cwareid { get; set; }
        public string Issave { get; set; }
    }
}