// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempStockCheckedbill
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Nocode { get; set; }
        public string Ctickecode { get; set; }
        public string Oraclecode { get; set; }
        public string Cwareid { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public string Qty { get; set; }
        public string Operatorno { get; set; }
        public string Bz { get; set; }
        public string Createuser { get; set; }
        public string Sncode { get; set; }
        public string Datecode { get; set; }
    }
}