// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempOutTransportationplan
    {
        public string Id { get; set; }
        public string Oldasncode { get; set; }
        public string Oldasnids { get; set; }
        public string So { get; set; }
        public string Soline { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Qty { get; set; }
        public string Newasncode { get; set; }
        public string Newasnids { get; set; }
        public DateTime? Createtime { get; set; }
    }
}