// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempBaseClient
    {
        public string Id { get; set; }
        public string Cclientid { get; set; }
        public string Cclientname { get; set; }
        public string Cstatus { get; set; }
        public string Ccontactperson { get; set; }
        public string Cphone { get; set; }
        public string Caddress { get; set; }
        public string Ctype { get; set; }
        public string Calias { get; set; }
        public string Ilever { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Ddefine3 { get; set; }
        public string Ddefine4 { get; set; }
        public string Idefine5 { get; set; }
        public string Cmemo { get; set; }
        public string Cerpcode { get; set; }
        public string Createtime { get; set; }
        public string Createowner { get; set; }
        public string Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public string Companyno { get; set; }
        public string Strongholdno { get; set; }
        public string Organizationno { get; set; }
        public int? Issave { get; set; }
    }
}