// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempTableStockPositionInfoT
    {
        public int? RowNum { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Palletcode { get; set; }
        public string Qty { get; set; }
        public string Datecode { get; set; }
        public string Cinvcode { get; set; }
        public string Ids { get; set; }
    }
}