// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempStockCheckedbillSn
    {
        public string Ids { get; set; }
        public string StockCheckbillDIds { get; set; }
        public string Checktype { get; set; }
        public string Sncode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Qty { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
    }
}