// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempStockcurrent1
    {
        public string Asnid { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Totleqty { get; set; }
        public string Userno { get; set; }
        public DateTime? Createdate { get; set; }
        public string Ctype { get; set; }
        public string Guid { get; set; }
    }
}