// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempTableAllocateT
    {
        public int? RowNum { get; set; }
        public string Cwarename { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cdatecode { get; set; }
        public string Iqty { get; set; }
        public string Ioccupyqty { get; set; }
        public string Locknum { get; set; }
        public string Palletcode { get; set; }
        public string Datecode { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Cticketcode { get; set; }
    }
}