// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempEbsResult
    {
        public DateTime TransactionDate { get; set; }
        public string Attribute11 { get; set; }
        public decimal? TransactionSourceId { get; set; }
        public string SubinventoryCode { get; set; }
        public decimal? LocatorId { get; set; }
        public decimal? InventoryItemId { get; set; }
        public string Attribute7 { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? Qty2 { get; set; }
    }
}