// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempLessCinvcode
    {
        public string Id { get; set; }
        public string Cerpcode { get; set; }
        public string Cinvcode { get; set; }
        public string Deptname { get; set; }
        public decimal? Requirenum { get; set; }
        public decimal? Issuednum { get; set; }
        public decimal? Noissuednum { get; set; }
        public decimal? Stockcannum { get; set; }
        public decimal? Nowstocklessnum { get; set; }
        public decimal? Acceptancenum { get; set; }
        public decimal? Inbillnum { get; set; }
        public decimal? Lesscinnum { get; set; }
    }
}