// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempStockSnreset
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cpositioncode { get; set; }
        public string Sncode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? SnQty { get; set; }
        public decimal? Flag { get; set; }
        public decimal? Sntype { get; set; }
        public string Createuser { get; set; }
    }
}