// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempUserArea
    {
        public string Userno { get; set; }
        public string Username { get; set; }
        public string Areaname { get; set; }
    }
}