// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempBaseDepartment
    {
        public string Id { get; set; }
        public int? ErrorFlag { get; set; }
        public string Departmentno { get; set; }
        public string Departmentname { get; set; }
    }
}