// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempOutasnId
    {
        public string Id { get; set; }
        public string Asnid { get; set; }
        public string Groupid { get; set; }
    }
}