// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempOrdercompissue
    {
        public string Id { get; set; }
        public string Tuserno { get; set; }
        public string Cerpcode { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Wmsyfl { get; set; }
        public decimal? Tlnum { get; set; }
        public decimal? Clnum { get; set; }
        public decimal? Ctnum { get; set; }
        public decimal? RequiredQuantity { get; set; }
        public decimal? Wfanum { get; set; }
        public decimal? Cfnum { get; set; }
        public decimal? Sfnum { get; set; }
        public decimal? Compnum { get; set; }
        public decimal? Nocompnum { get; set; }
        public string Compcinvcode { get; set; }
        public string TypeSmt { get; set; }
        public decimal? Cfhdkznum { get; set; }
        public decimal? Cfhdwkznum { get; set; }
        public decimal? Wlpsnum { get; set; }
        public decimal? Clcfnum { get; set; }
    }
}