// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempSelectasnd
    {
        public string AsnIds { get; set; }
        public string AsnId { get; set; }
        public string Userno { get; set; }
        public string Guid { get; set; }
        public DateTime Createdate { get; set; }
        public string Id { get; set; }
    }
}