// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempOfZyl
    {
        public string ItemId { get; set; }
        public string Storage { get; set; }
        public decimal? Totalnum { get; set; }
        public string Cticketcode { get; set; }
        public string Flag { get; set; }
    }
}