// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TempStockCheck
    {
        public string Id { get; set; }
        public string Whid { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
        public int? Updatemark { get; set; }
        public DateTime? Updatetime { get; set; }
        public DateTime? Createtime { get; set; }
    }
}