// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class TransLog
    {
        public decimal Sequence { get; set; }
        public string Sqlcode { get; set; }
        public string Sqlerror { get; set; }
        public DateTime Errordate { get; set; }
    }
}