// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class UserFunction
    {
        public string Id { get; set; }
        public string Userno { get; set; }
        public string Username { get; set; }
        public string Funcno { get; set; }
        public string Funcname { get; set; }
        public string Extend1 { get; set; }
        public string Modno { get; set; }
    }
}