// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VBarPalletM
    {
        public string Id { get; set; }
        public string Palletno { get; set; }
        public string CartonNo { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal? Qty { get; set; }
    }
}