// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VBarSnSplitDQuery
    {
        public string Id { get; set; }
        public string Sn { get; set; }
        public string NewSn { get; set; }
        public string Cinvcode { get; set; }
        public decimal? SnQty { get; set; }
        public decimal? NewSnQty { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public string Cpositioncode { get; set; }
        public string Type { get; set; }
    }
}