// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VBaseBarSnquery
    {
        public string Id { get; set; }
        public string SnCode { get; set; }
        public string Datecode { get; set; }
        public string Bonded { get; set; }
        public decimal? Validitydate { get; set; }
        public string Vendor { get; set; }
        public string VendorName { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Cinvcode { get; set; }
        public string CinvcodeName { get; set; }
        public decimal? Quantity { get; set; }
        public string SnType { get; set; }
        public DateTime? CreateTime { get; set; }
        public string CreateOwner { get; set; }
        public DateTime? LastUpdTime { get; set; }
        public string LastUpdOwner { get; set; }
        public string Cpositioncode { get; set; }
        public string PoNumber { get; set; }
        public string BatchNumber { get; set; }
        public decimal? BatchQty { get; set; }
        public string BarType { get; set; }
        public int? SerialNo { get; set; }
    }
}