// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VCargospaceReport
    {
        public string Cwareid { get; set; }
        public string Cwarename { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cstatus { get; set; }
        public decimal? Imaxcapacity { get; set; }
        public string Calias { get; set; }
        public string Ctype { get; set; }
        public decimal? Ipermitmix { get; set; }
        public string Id { get; set; }
        public string Statusname { get; set; }
        public string Ipermitmixname { get; set; }
    }
}