// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VCinvcodeControl
    {
        public string Mo { get; set; }
        public string Cinvcode { get; set; }
        public string Flag { get; set; }
    }
}