// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VEmtInemtlist
    {
        public string SnCode { get; set; }
        public string Palletcode { get; set; }
        public string Erpcode { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Qty { get; set; }
        public DateTime? Creatertime { get; set; }
        public string Cticketcode { get; set; }
        public decimal? CriticalPart { get; set; }
        public string Cerpcode { get; set; }
        public string Cstatus { get; set; }
        public string Id { get; set; }
        public string Worktype { get; set; }
        public string Cdefine2 { get; set; }
        public string WorktypeName { get; set; }
    }
}