// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VGdMinsets
    {
        public string Gdno { get; set; }
        public string Minsets { get; set; }
    }
}