// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VGetPolist
    {
        public string Id { get; set; }
        public string Pono { get; set; }
        public string Vendorid { get; set; }
        public string Vendorname { get; set; }
    }
}