// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class ViewInventoryTurnin
    {
        public string Ids { get; set; }
        public string Stype { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Sncode { get; set; }
        public decimal? Datecode { get; set; }
        public string Weeks { get; set; }
        public decimal? Iquantity { get; set; }
        public DateTime Dindate { get; set; }
        public string Cinpersoncode { get; set; }
        public string Username { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
        public string Stypename { get; set; }
    }
}