// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class ViewTransactionSn
    {
        public long? Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Ctopositioncode { get; set; }
        public string Ctoposition { get; set; }
        public string SnCode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Quantity { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public string Stype { get; set; }
        public string Weeks { get; set; }
        public string Cerpcode { get; set; }
        public string Typecode { get; set; }
        public string Typename { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
        public string Stypename { get; set; }
    }
}