// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VInAssitList
    {
        public string Id { get; set; }
        public string Cticketcode { get; set; }
        public string Casnid { get; set; }
        public string Cerpcode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cpo { get; set; }
        public string Typename { get; set; }
        public string Cvender { get; set; }
        public string Itype { get; set; }
    }
}