// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VInassitReport
    {
        public string Id { get; set; }
        public string Inasncticketcode { get; set; }
        public string Inassicticketcode { get; set; }
        public string Cerpcode { get; set; }
        public string Cwareid { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal? Iquantity { get; set; }
        public string Typename { get; set; }
        public string Cinpersoncode { get; set; }
        public DateTime? Dindate { get; set; }
        public string Intype { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
    }
}