// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VInbillDandSn
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string CstatusName { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cerpcodeline { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public DateTime? Dindate { get; set; }
        public string Inbilltype { get; set; }
        public int? Lineid { get; set; }
        public string SnCode { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Quantity { get; set; }
        public string PalletCode { get; set; }
    }
}