// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VJianhuoReport
    {
        public string Id { get; set; }
        public string Cwareid { get; set; }
        public string Cwarename { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cinvcode { get; set; }
        public decimal Iquantity { get; set; }
        public string Typename { get; set; }
        public string Coutpersoncode { get; set; }
        public DateTime Doutdate { get; set; }
        public string Outassitcticketcode { get; set; }
        public string Cerpcode { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public decimal Itype { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
        public string Cerpcode1 { get; set; }
        public string Cspecifications { get; set; }
    }
}