// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VMergeErpCodeReportTest
    {
        public string Ids { get; set; }
        public string Cerpcode { get; set; }
    }
}