// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VOrderFinishStock
    {
        public Guid? Id { get; set; }
        public string OrderNo { get; set; }
        public string CustomOrderNo { get; set; }
        public string CustomId { get; set; }
        public string CustomName { get; set; }
        public int OrderLine { get; set; }
        public string CinvCode { get; set; }
        public string CinvName { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cwarehouse { get; set; }
        public decimal? AllQty { get; set; }
        public decimal? LockQty { get; set; }
        public DateTime? LastUpdateTime { get; set; }
    }
}