// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VOutBillAdj
    {
        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditpersoncode { get; set; }
        public DateTime? Dauditdate { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Cerpcode { get; set; }
        public string Cmemo { get; set; }
        public string Cso { get; set; }
        public decimal Itype { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Cclientcode { get; set; }
        public string Cclient { get; set; }
        public string OutVendor { get; set; }
        public decimal? IsMerge { get; set; }
        public string FgCinvcode { get; set; }
        public string MergeId { get; set; }
        public string Site { get; set; }
        public decimal? IsSmt { get; set; }
        public string ClassCode { get; set; }
        public decimal? IsSemi { get; set; }
        public decimal? SpecialOut { get; set; }
        public decimal? CriticalPart { get; set; }
        public decimal? FgQty { get; set; }
        public decimal? IsAssiting { get; set; }
        public decimal? IsWhole { get; set; }
        public string Reasoncode { get; set; }
        public string Worktype { get; set; }
    }
}