// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VOutasnD
    {
        public string Id { get; set; }
        public string Ids { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cerpcodeline { get; set; }
        public decimal? Iquantity { get; set; }
    }
}