// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VOutmixedD
    {
        public string Createrusername { get; set; }
        public string Id { get; set; }
        public string Ids { get; set; }
        public string Outcticketcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal Qty { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cstatus { get; set; }
        public string Createruser { get; set; }
        public DateTime? Creatertime { get; set; }
        public string Remark { get; set; }
        public string Cdefiend1 { get; set; }
        public string Cdefiend2 { get; set; }
        public string Cdefiend3 { get; set; }
    }
}