// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VOutbillSn
    {
        public string Id { get; set; }
        public string OutbillId { get; set; }
        public string OutbillDIds { get; set; }
        public string SnCode { get; set; }
        public decimal? Datecode { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Quantity { get; set; }
        public string Worktype { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastvpdtime { get; set; }
        public string Lastvpdowner { get; set; }
        public string ScanIds { get; set; }
        public decimal? LineQty { get; set; }
        public decimal? Sntype { get; set; }
        public string Furnaceno { get; set; }
        public string Outbilltype { get; set; }
        public string Palletcode { get; set; }
        public string Cso { get; set; }
        public string Vendorcode { get; set; }
        public string Rulecode { get; set; }
        public decimal? Allqty { get; set; }
    }
}