// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPartunionbom
    {
        public string Id { get; set; }
        public string Cpartnumber { get; set; }
        public string Cpartname { get; set; }
        public string Ctype { get; set; }
    }
}