// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaInAsnEmtList
    {
        public string Erpcode { get; set; }
        public string Cticketcode { get; set; }
        public string Ownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Worktype { get; set; }
        public string WorktypeName { get; set; }
        public string Userno { get; set; }
        public string Id { get; set; }
        public string Itype { get; set; }
        public string Typename { get; set; }
    }
}