// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaMergeOutBillDeliverList
    {
        public string Id { get; set; }
        public string Cticketcode { get; set; }
        public string Otype { get; set; }
        public string Cerpcode { get; set; }
        public string Cso { get; set; }
        public string Outcticketcode { get; set; }
    }
}