// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaInemtQueryList
    {
        public string SnCode { get; set; }
        public string Palledcode { get; set; }
        public string Statusname { get; set; }
        public string Cstatus { get; set; }
        public string Erpcode { get; set; }
        public string Cinvcode { get; set; }
        public decimal Qty { get; set; }
        public DateTime? Emttime { get; set; }
        public string Emtuserno { get; set; }
        public string Cticketcode { get; set; }
        public string Id { get; set; }
        public string Worktype { get; set; }
        public string Worktypename { get; set; }
    }
}