// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaOutAssitAll
    {
        public string Ids { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal Inum { get; set; }
        public decimal Yjnum { get; set; }
        public decimal? Synum { get; set; }
        public string Cspecifications { get; set; }
        public string Cticketcode { get; set; }
        public string Asncticketcode { get; set; }
    }
}