// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaTemporaryInList
    {
        public string Id { get; set; }
        public string Cerpcode { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Itype { get; set; }
        public string Typename { get; set; }
        public string Statusname { get; set; }
        public string Ccreateownercode { get; set; }
    }
}