// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaQueryOutBill
    {
        public string Id { get; set; }
        public string Cerpcode { get; set; }
        public string Cticketcode { get; set; }
        public string Otype { get; set; }
        public decimal Otypeid { get; set; }
        public DateTime Dindate { get; set; }
        public string Cstatus { get; set; }
        public string Palletcode { get; set; }
    }
}