// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaQueryOutAssit
    {
        public string Ids { get; set; }
        public string Cticketcode { get; set; }
        public string Casnid { get; set; }
        public string Cso { get; set; }
        public string Cerpcode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string OcriticalPart { get; set; }
        public decimal? CriticalPart { get; set; }
        public string Typename { get; set; }
        public string Shift { get; set; }
        public DateTime? StartDate { get; set; }
        public string SecCinvcode { get; set; }
        public decimal Itype { get; set; }
        public string Cinvcode { get; set; }
        public string Special { get; set; }
        public string SmtType { get; set; }
    }
}