// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaOutAssitList
    {
        public string Id { get; set; }
        public string Cticketcode { get; set; }
        public string Cerpcode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Typename { get; set; }
        public string Shift { get; set; }
        public DateTime? StartDate { get; set; }
        public string SecCinvcode { get; set; }
        public string Itype { get; set; }
        public decimal? Asnqty { get; set; }
        public decimal? Tempqty { get; set; }
    }
}