// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaQueryTempInBillD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal? Datecode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Iquantity { get; set; }
        public decimal? Sntype { get; set; }
        public string Cspecifications { get; set; }
        public DateTime Dindate { get; set; }
    }
}