// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VPdaOutBillItems
    {
        public string Cinvcode { get; set; }
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Status { get; set; }
        public decimal? Yfnum { get; set; }
        public decimal? Iquantity { get; set; }
        public decimal? Yjfsl { get; set; }
        public string Cinvname { get; set; }
        public decimal? LineQty { get; set; }
        public decimal? Total { get; set; }
        public decimal? Ccjfsl { get; set; }
    }
}