// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VQuickMixed
    {
        public string Id { get; set; }
        public string Ids { get; set; }
        public string Cerpcode { get; set; }
        public string Cticketcode { get; set; }
        public string Palletcode { get; set; }
        public decimal Qty { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal Otype { get; set; }
        public string Otypename { get; set; }
    }
}