// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VScanInAssitInfo
    {
        public string CPositionCode { get; set; }
        public string CPosition { get; set; }
        public string CInvCode { get; set; }
        public string Cinvname { get; set; }
        public string Cspecifications { get; set; }
        public decimal INum { get; set; }
        public string Cticketcode { get; set; }
        public int? CriticalPart { get; set; }
        public string Caccountid { get; set; }
        public decimal Dounted { get; set; }
    }
}