// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VStockCheckedbillList
    {
        public string Cerpcode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public decimal Iquantity { get; set; }
        public string Ccheckpersoncode { get; set; }
        public string Cticketcode { get; set; }
        public string Cinvname { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine2 { get; set; }
    }
}