// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VStockForerp
    {
        public string 仓库 { get; set; }
        public string 料号 { get; set; }
        public string 品名 { get; set; }
        public string 助记码 { get; set; }
        public string 规格 { get; set; }
        public decimal? 数量 { get; set; }
    }
}