// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VStockElectBinCard
    {
        public string Id { get; set; }
        public string Cwarehouse { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cposition { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Qty { get; set; }
        public string Cdefaultvendor { get; set; }
        public string Cspecifications { get; set; }
        public string Sncode { get; set; }
        public string Furnaceno { get; set; }
        public string Productcode { get; set; }
        public string Cdefine1 { get; set; }
        public string Leader { get; set; }
        public string Cwarename { get; set; }
        public decimal? Datecode { get; set; }
        public string Stocktype { get; set; }
        public string Cvendor { get; set; }
        public string InBillTypeName { get; set; }
    }
}