// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VSysParameter
    {
        public string Id { get; set; }
        public string FlagId { get; set; }
        public string FlagName { get; set; }
        public string FlagType { get; set; }
        public decimal? Sortid { get; set; }
        public string Memo { get; set; }
        public string FlagGuid { get; set; }
        public string Languageid { get; set; }
    }
}