// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VTempBaseArea
    {
        public string Id { get; set; }
        public string 区域名称 { get; set; }
        public string 备料储位编号 { get; set; }
        public string 备料储位名称 { get; set; }
        public string 是否超发 { get; set; }
    }
}