// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VTempBaseDepartment
    {
        public string 部门编码 { get; set; }
        public string 部门名称 { get; set; }
    }
}