// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class VUserDept
    {
        public string Id { get; set; }
        public string Userno { get; set; }
        public string Username { get; set; }
        public string Deptname { get; set; }
        public string Deptno { get; set; }
        public string Fatherno { get; set; }
        public string PUserNo { get; set; }
        public string PUserName { get; set; }
        public string PEmail { get; set; }
    }
}