// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class WarnCargoMail
    {
        public string Id { get; set; }
        public string Cargocode { get; set; }
        public string Waretypename { get; set; }
        public string Warehousename { get; set; }
        public string Personliable { get; set; }
        public string Mail { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Cdefine3 { get; set; }
        public string Createuser { get; set; }
        public DateTime? Createdate { get; set; }
        public string Lastupdateuser { get; set; }
        public DateTime? Lastupdatedate { get; set; }
    }
}