// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class WcsTaskProcessD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Loc { get; set; }
        public string Newloc { get; set; }
        public string Machine { get; set; }
        public string Asrsid { get; set; }
        public string Cstatus { get; set; }
        public string Cdefiend1 { get; set; }
        public string Cdefiend2 { get; set; }
        public string Cdefiend3 { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public string Steps { get; set; }
        public DateTime? Updatedtime { get; set; }
    }
}