// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class WipnegativeissueTemp
    {
        public string Id { get; set; }
        public string WipEntityName { get; set; }
        public string WipEntityId { get; set; }
        public string QuantityIssued { get; set; }
        public DateTime? Createtime { get; set; }
        public string InventoryItemId { get; set; }
    }
}