// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class WmsTableRelation
    {
        public string TableId { get; set; }
        public string TableName { get; set; }
        public string HisTable { get; set; }
        public string ChildTableId { get; set; }
        public decimal? Seq { get; set; }
        public string Reservefield1 { get; set; }
        public string Reservefield2 { get; set; }
        public string Reservefield3 { get; set; }
    }
}