// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class WriteBackTimeSet
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string TransactionType { get; set; }
        public string Cticketcode { get; set; }
        public DateTime? ExchangeTime { get; set; }
        public DateTime? ExpirationTime { get; set; }
        public string CreateOwner { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastUpdOwner { get; set; }
        public DateTime? LastUpdDate { get; set; }
    }
}