// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0001
{
    public partial class Zsict1User
    {
        public string Userno { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public decimal? Sex { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public decimal? Type { get; set; }
        public decimal? Flag { get; set; }
        public DateTime? Lastmodifiedtime { get; set; }
        public string Company { get; set; }
        public string Rootdept { get; set; }
        public decimal? Comptype { get; set; }
        public decimal? Ddomain { get; set; }
        public string Id { get; set; }
        public string EmpId { get; set; }
        public string Extend1 { get; set; }
        public string Extend2 { get; set; }
        public string Extend3 { get; set; }
        public string Extend4 { get; set; }
        public string Extend5 { get; set; }
        public decimal? Extend6 { get; set; }
        public decimal? Extend7 { get; set; }
        public decimal? Extend8 { get; set; }
        public decimal? Extend9 { get; set; }
        public decimal? Extend10 { get; set; }
        public DateTime? Extend12 { get; set; }
        public DateTime? Extend13 { get; set; }
        public DateTime? Extend11 { get; set; }
        public string Lastmodifieder { get; set; }
        public string LoginGuid { get; set; }
        public DateTime? LoginTime { get; set; }
        public string Extend14 { get; set; }
        public string Extend15 { get; set; }
        public string Extend16 { get; set; }
        public string Extend17 { get; set; }
        public string Extend18 { get; set; }
        public byte[] Blob1 { get; set; }
        public byte[] Blob2 { get; set; }
        public byte[] Blob3 { get; set; }
        public byte[] Blob4 { get; set; }
        public byte[] Blob5 { get; set; }
        public string Filename4Blob1 { get; set; }
        public string Filename4Blob2 { get; set; }
        public string Filename4Blob3 { get; set; }
        public string Filename4Blob4 { get; set; }
        public string Filename4Blob5 { get; set; }
        public string MimeType4Blob1 { get; set; }
        public string MimeType4Blob2 { get; set; }
        public string MimeType4Blob3 { get; set; }
        public string MimeType4Blob4 { get; set; }
        public string MimeType4Blob5 { get; set; }
    }
}