// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class AllocateScanQty
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Qty { get; set; }
        public string Scanuser { get; set; }
        public DateTime? Scandate { get; set; }
        public string Sncode { get; set; }
        public decimal? Datecode { get; set; }
        public string AllocateDIds { get; set; }
        public string ScanSn { get; set; }
        public decimal? ScanQty { get; set; }
        public decimal? ScanType { get; set; }
    }
}