// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BarSnSplit
    {
        public BarSnSplit()
        {
            BarSnSplitD = new HashSet<BarSnSplitD>();
        }

        public string Id { get; set; }
        public string SplitSn { get; set; }
        public decimal SplitSnQty { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public string Createowner { get; set; }
        public DateTime? Createtime { get; set; }

        public virtual ICollection<BarSnSplitD> BarSnSplitD { get; set; }
    }
}