// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BarType
    {
        public string Id { get; set; }
        public string Typename { get; set; }
        public string Type { get; set; }
        public string BarcodeType { get; set; }
        public string Mix { get; set; }
        public decimal? MaxQty { get; set; }
        public DateTime? Createtime { get; set; }
        public string Craeteowner { get; set; }
        public DateTime? Lastmodifytime { get; set; }
        public string Lastmodifyowner { get; set; }
    }
}