// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseClient
    {
        public string Id { get; set; }
        public string Cclientid { get; set; }
        public string Cclientname { get; set; }
        public string Cstatus { get; set; }
        public string Ccontactperson { get; set; }
        public string Cphone { get; set; }
        public string Caddress { get; set; }
        public string Ctype { get; set; }
        public string Calias { get; set; }
        public decimal? Ilever { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Cmemo { get; set; }
        public string Cerpcode { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
    }
}