// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseWarehouseTemp
    {
        public string Cwarename { get; set; }
        public string Cwareid { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Leadercode { get; set; }
        public string Leader { get; set; }
        public string Cmemo { get; set; }
        public string Leaderphone { get; set; }
        public string Cstatus { get; set; }
        public string Bonded { get; set; }
        public string Createowner { get; set; }
        public string Companyno { get; set; }
        public string Strongholdno { get; set; }
        public string Organizationno { get; set; }
        public string Id { get; set; }
        public int? Flag { get; set; }
    }
}