// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseAsrsDb
    {
        public string Id { get; set; }
        public string DbIp { get; set; }
        public string DbDatebase { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Memo { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateuser { get; set; }
    }
}