// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseBarcodePrintD
    {
        public string Id { get; set; }
        /// <summary>
        /// 打印规则
        /// </summary>
        public string PrintId { get; set; }
        /// <summary>
        /// 序号
        /// </summary>
        public int PrintSeq { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string PrintItemName { get; set; }
        /// <summary>
        /// 类型
        /// </summary>
        public string PrintItemType { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string PrintRemark { get; set; }
        public string IsNeedVal { get; set; }
    }
}