// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseRgvTvPackageNo
    {
        public string Id { get; set; }
        public string Lineid { get; set; }
        public string Rgvareaid { get; set; }
        public string Packageno { get; set; }
        public string Createuser { get; set; }
        public DateTime Createtime { get; set; }
        public string Remark { get; set; }
    }
}