// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseResources
    {
        public string Id { get; set; }
        public string SourceKey { get; set; }
        public string SourceValue { get; set; }
        public string LanguageId { get; set; }
        public string ModuleId { get; set; }
        public string Remark { get; set; }
        public string Cdefined1 { get; set; }
        public string Cdefined2 { get; set; }
        public string Cdefined3 { get; set; }
        public string Cdefined4 { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateTime { get; set; }
        public string ModifyUser { get; set; }
        public DateTime? Modifytime { get; set; }
        public string Cstatus { get; set; }
    }
}