// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseCraneconfigDTrade
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        /// <summary>
        /// 交易名
        /// </summary>
        public string Name { get; set; }
        public string Type { get; set; }
        public string Erpcode { get; set; }
        public string CraneId { get; set; }
        public string CraneName { get; set; }
        public string SiteId { get; set; }
        public string SiteName { get; set; }
    }
}