// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseReplacepalletcodeRecord
    {
        public string Id { get; set; }
        public int Number { get; set; }
        public string OldPalletcode { get; set; }
        public string ReplacePalletcode { get; set; }
        public string Cticketcode { get; set; }
        public string Palletcode { get; set; }
        public string Operationuser { get; set; }
        public DateTime Operationtime { get; set; }
        public string Defined1 { get; set; }
        public DateTime? Defined2 { get; set; }
        public string Defined3 { get; set; }
        public DateTime? Defined4 { get; set; }
        public string Defined5 { get; set; }
        public string Defined6 { get; set; }
    }
}