// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseOperatorAreaNew
    {
        public string Caccountid { get; set; }
        public string AreaId { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Ccreateowner { get; set; }
    }
}