// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseInterfacelog202003
    {
        public string Id { get; set; }
        public string Ticketcode { get; set; }
        public string Erpcode { get; set; }
        public string Typeid { get; set; }
        public string Methodname { get; set; }
        public string Errormsg { get; set; }
        public DateTime? Createdate { get; set; }
        public string Createowner { get; set; }
        public string Remark { get; set; }
        public string Bo { get; set; }
        public string Typename { get; set; }
    }
}