// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class CmdEquipTask
    {
        /// <summary>
        /// 主键，自增长
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 设备类型0，RGV；1,升降机
        /// </summary>
        public int Equiptype { get; set; }
        /// <summary>
        /// 命令编号：1～29998
        /// </summary>
        public string Cmdsno { get; set; }
        /// <summary>
        /// 1：入库 2：出库 3：拣料出 4：站对站（FROM） 5:拣料入 6：站对站（TO）7：盘点出 8：盘点入
        /// </summary>
        public string Cmdmode { get; set; }
        /// <summary>
        /// 起点站点编号
        /// </summary>
        public string Startstnno { get; set; }
        /// <summary>
        /// 终点站点编号
        /// </summary>
        public string Endstnno { get; set; }
        /// <summary>
        /// 任务状态 0，未开始 1，已下发 7，已完成
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 完成的命令编号，wcs自用
        /// </summary>
        public string Trnno { get; set; }
        /// <summary>
        /// 命令下发时间，WCS自用
        /// </summary>
        public string Acttime { get; set; }
        /// <summary>
        /// 命令完成时间，WCS自用
        /// </summary>
        public string Endtime { get; set; }
        /// <summary>
        /// 任务生成者
        /// </summary>
        public string CreateOwner { get; set; }
        /// <summary>
        /// 任务生成时间
        /// </summary>
        public DateTime Createtime { get; set; }
    }
}