// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class CmdMstRgv
    {
        public int WmsTskId { get; set; }
        public string CmdSno { get; set; }
        public string CmdSts { get; set; }
        public string Prt { get; set; }
        public string StnNo { get; set; }
        public string CmdMode { get; set; }
        public string Loc { get; set; }
        public string NewLoc { get; set; }
        public string LocSize { get; set; }
        public string RodId { get; set; }
        public string Trace { get; set; }
        public string TrnDate { get; set; }
        public string ActTime { get; set; }
        public string EndTime { get; set; }
        public string Result { get; set; }
        public string TrnNo { get; set; }
        public int? BillingStatus { get; set; }
        public string CreateUser { get; set; }
        public string BillingNo { get; set; }
        public string CmdNo { get; set; }
        public string LineId { get; set; }
        public string Plcd51 { get; set; }
        public string Cticketcode { get; set; }
        public string Packageno { get; set; }
        public string Remark { get; set; }
        public int? Updata { get; set; }
        public string Msg { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Cdefine3 { get; set; }
        public string Height { get; set; }
        public string Reason { get; set; }
        public string Pc { get; set; }
        public string CraneStataus { get; set; }
        public string AreaId { get; set; }
    }
}