// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class DatecodeStockCurrentDetail
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Qty { get; set; }
        public string Createuser { get; set; }
        public DateTime? Createdate { get; set; }
        public string Lockuser { get; set; }
        public DateTime? Locktime { get; set; }
    }
}