// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class DateEmpTempbak
    {
        public string 仓库 { get; set; }
        public string 区块 { get; set; }
        public string 仓管员1 { get; set; }
        public string 仓管员2 { get; set; }
        public string 仓管员3 { get; set; }
        public string 仓管员4 { get; set; }
        public string 仓管员5 { get; set; }
        public string 仓管员6 { get; set; }
        public string 仓管员7 { get; set; }
        public string 仓管员8 { get; set; }
        public string 仓管员9 { get; set; }
        public string 仓管员10 { get; set; }
        public string 仓管员11 { get; set; }
        public string 仓管员12 { get; set; }
        public string 仓管员13 { get; set; }
        public string 仓管员14 { get; set; }
        public string 仓管员15 { get; set; }
        public string 仓管员16 { get; set; }
        public string 仓管员17 { get; set; }
        public string 仓管员18 { get; set; }
        public string 仓管员19 { get; set; }
        public string 仓管员20 { get; set; }
        public string 币别 { get; set; }
        public string 储位 { get; set; }
        public string 料号 { get; set; }
        public string 单位 { get; set; }
        public string 单位最小数量 { get; set; }
        public string 储位最大容易 { get; set; }
        public string 优先级1 { get; set; }
        public string 优先级2 { get; set; }
        public string Memo { get; set; }
    }
}