// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class DepartmentLineInfo
    {
        public string Id { get; set; }
        public string Departmentno { get; set; }
        public decimal Type { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
    }
}