// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class GPartMapWms
    {
        public string GrNo { get; set; }
        public decimal? ItemNo { get; set; }
        public string PartNo { get; set; }
        public string PartSn { get; set; }
        public decimal? Qty { get; set; }
        public string Flag { get; set; }
    }
}