// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class InasnIa
    {
        public InasnIa()
        {
            InasnIaD = new HashSet<InasnIaD>();
        }

        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditpersoncode { get; set; }
        public DateTime? Dauditdate { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Cmemo { get; set; }
        public string Tradecode { get; set; }
        public string Currency { get; set; }
        public string Ddefine1 { get; set; }
        public string Ddefine2 { get; set; }
        public string Idefine3 { get; set; }
        public string Cvendercode { get; set; }
        public string Cvender { get; set; }
        public string Batchno { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public string Cerpcode { get; set; }
        public string Pono { get; set; }

        public virtual ICollection<InasnIaD> InasnIaD { get; set; }
    }
}