// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class Intype
    {
        public string Typeid { get; set; }
        public string Typename { get; set; }
        public string Cerpcode { get; set; }
        public string TransactionActionId { get; set; }
        public string TransactionSourceTypeId { get; set; }
        public string Attribute1 { get; set; }
        public string TypeClass { get; set; }
        public string IsZf { get; set; }
        public DateTime? DisableDate { get; set; }
        public string ErpSourceTypename { get; set; }
        public string ErpSourceTypecode { get; set; }
        public string Enable { get; set; }
        public string Enableuser { get; set; }
        public DateTime? Enabledate { get; set; }
        public string Createuser { get; set; }
        public DateTime? Createdate { get; set; }
        public int? IsQuery { get; set; }
        public string IsMatchSo { get; set; }
        public string IsMatchVendor { get; set; }
    }
}