// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class OutHandover
    {
        public string Id { get; set; }
        public string OutbillDId { get; set; }
        public decimal? Qty { get; set; }
        public string Createowner { get; set; }
        public DateTime Createtime { get; set; }
    }
}