// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class Outmixed
    {
        public string Id { get; set; }
        public string Mixedcode { get; set; }
        public string Erpcode { get; set; }
        public string Outcticketcode { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal Otype { get; set; }
        public string Cstatus { get; set; }
        public string Startsite { get; set; }
        public string Endsite { get; set; }
        public string Createruser { get; set; }
        public DateTime? Creatertime { get; set; }
        public string Modifyuser { get; set; }
        public DateTime? Modifytime { get; set; }
        public string Cdefiend1 { get; set; }
        public string Cdefiend2 { get; set; }
        public string Cdefiend3 { get; set; }
        public string Remark { get; set; }
        public string Mixedsite { get; set; }
    }
}