// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class OutorderD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        /// <summary>
        /// 项次
        /// </summary>
        public int OrderLine { get; set; }
        /// <summary>
        /// 料号
        /// </summary>
        public string CinvCode { get; set; }
        /// <summary>
        /// 料名称
        /// </summary>
        public string CinvName { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public decimal? Iquantity { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public DateTime? SaleDate { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public int? Status { get; set; }
        /// <summary>
        /// 预留字段1
        /// </summary>
        public string Define1 { get; set; }
        /// <summary>
        /// 预留字段2
        /// </summary>
        public string Define2 { get; set; }
        /// <summary>
        /// 预留字段3
        /// </summary>
        public string Define3 { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? CreateTime { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string CreateOwner { get; set; }
        /// <summary>
        /// 最后修改时间
        /// </summary>
        public DateTime? LastUpdateTime { get; set; }
        /// <summary>
        /// 最后修改人
        /// </summary>
        public string LastUpdateOwner { get; set; }
        public decimal? FinishQty { get; set; }
    }
}