// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class PdaLessErpcode
    {
        public string Cerpcode { get; set; }
        public string Cinvcode { get; set; }
        public string Searchuser { get; set; }
        public DateTime? Createtime { get; set; }
    }
}