// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class PlcCmdMst
    {
        public string Id { get; set; }
        public string LineId { get; set; }
        public string D500 { get; set; }
        public string D501 { get; set; }
        public string D502 { get; set; }
        public string D503 { get; set; }
        public string D504 { get; set; }
        public string D505 { get; set; }
        public string D506 { get; set; }
        public string D507 { get; set; }
        public string D508 { get; set; }
        public string D509 { get; set; }
        public string D510 { get; set; }
        public string D511 { get; set; }
        public string D512 { get; set; }
        public string D513 { get; set; }
        public string D514 { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Remark { get; set; }
    }
}