// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class Proclogs
    {
        public string Msg { get; set; }
        public string Guid { get; set; }
        public DateTime? Datetimes { get; set; }
    }
}