// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class R09WhStockDtLXCnt
    {
        public string Dt { get; set; }
        public string L { get; set; }
        public int? X { get; set; }
        public int? Cnt { get; set; }
    }
}