// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class RptStockDiscrepencyTest
    {
        public string Id { get; set; }
        public string Warehouseid { get; set; }
        public string Positionid { get; set; }
        public string Positionname { get; set; }
        public string Cpartnumber { get; set; }
        public string Cpartname { get; set; }
        public string EbsStockQty { get; set; }
        public string WmsStockQty { get; set; }
        public string DiscrepencyQty { get; set; }
        public DateTime CreateTime { get; set; }
        public string CreateOwner { get; set; }
    }
}