// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    /// <summary>
    /// 库存调整单
    /// </summary>
    public partial class StockAdjust
    {
        public string Id { get; set; }
        /// <summary>
        /// 制单人
        /// </summary>
        public string Ccreateownercode { get; set; }
        /// <summary>
        /// 制单日期
        /// </summary>
        public DateTime? Dcreatetime { get; set; }
        /// <summary>
        /// 审核人
        /// </summary>
        public string Cauditperson { get; set; }
        /// <summary>
        /// 审核日期
        /// </summary>
        public DateTime? Daudittime { get; set; }
        /// <summary>
        /// 单据号
        /// </summary>
        public string Cticketcode { get; set; }
        /// <summary>
        /// 状态（0 未处理,1 已完成,）
        /// </summary>
        public string Cstatus { get; set; }
        /// <summary>
        /// 调整日期
        /// </summary>
        public DateTime Dindate { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Cmemo { get; set; }
        /// <summary>
        /// ERP单号(生单过后返回)
        /// </summary>
        public string Cerpcode { get; set; }
        /// <summary>
        /// 自定义3
        /// </summary>
        public DateTime? Ddefine3 { get; set; }
        /// <summary>
        /// 自定义1
        /// </summary>
        public string Cdefine1 { get; set; }
        /// <summary>
        /// 自定义2
        /// </summary>
        public string Cdefine2 { get; set; }
        /// <summary>
        /// 自定义4
        /// </summary>
        public DateTime? Ddefine4 { get; set; }
        /// <summary>
        /// 自定义5
        /// </summary>
        public decimal? Idefine5 { get; set; }
        /// <summary>
        /// 调整类型( 0：调整入，1：调整出)
        /// </summary>
        public int Atype { get; set; }
    }
}