// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class StockCurrentSnReset
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 库存表id
        /// </summary>
        public string StockId { get; set; }
        /// <summary>
        /// sn编号
        /// </summary>
        public string Sncode { get; set; }
        /// <summary>
        /// 日期
        /// </summary>
        public decimal? Datecode { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public decimal? Qty { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public string Cstatus { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? Createtime { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string Createuser { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Cmemo { get; set; }
        /// <summary>
        /// sn类型
        /// </summary>
        public decimal? Sntype { get; set; }
        /// <summary>
        /// 分组id
        /// </summary>
        public string Groupid { get; set; }
        /// <summary>
        /// 料号
        /// </summary>
        public string Cinvcode { get; set; }
        /// <summary>
        /// 储位
        /// </summary>
        public string Cpositioncode { get; set; }
        /// <summary>
        /// 标签
        /// </summary>
        public string Flag { get; set; }
        /// <summary>
        /// 分组时间
        /// </summary>
        public DateTime? Grouptime { get; set; }
    }
}