// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class StockAlloScanD
    {
        public string Id { get; set; }
        public string AlloIds { get; set; }
        public string AlloId { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Ctopositioncode { get; set; }
        public string Ctoposition { get; set; }
        public string Csn { get; set; }
        public decimal? Cdatecode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public DateTime Dindate { get; set; }
        public string Cinpersoncode { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public decimal? Sntype { get; set; }
        public string Rulecode { get; set; }
    }
}