// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SysBilllog
    {
        public string Id { get; set; }
        public string Casetype { get; set; }
        public string Caseid { get; set; }
        public string Caseno { get; set; }
        public int? Stepid { get; set; }
        public string Steplog { get; set; }
        public string Remark { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
    }
}