// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SysJob
    {
        public string Id { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Jobname { get; set; }
        /// <summary>
        /// DLL 名称
        /// </summary>
        public string Dllname { get; set; }
        /// <summary>
        /// job类名称(包含命名空间)
        /// </summary>
        public string Classname { get; set; }
        /// <summary>
        /// 函数名称
        /// </summary>
        public string Functionname { get; set; }
        /// <summary>
        /// 每天执行频率类型 1 执行一次 2 间隔执行
        /// </summary>
        public int Dayfretype { get; set; }
        /// <summary>
        /// 每天执行一次的执行时间
        /// </summary>
        public string Oncedayfre { get; set; }
        /// <summary>
        /// 重复执行时的间隔(单位秒)
        /// </summary>
        public int? Splittime { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 开始运行时间
        /// </summary>
        public DateTime? Beginruntime { get; set; }
        /// <summary>
        /// 上次运行结束时间
        /// </summary>
        public DateTime? Lastendtime { get; set; }
        /// <summary>
        /// 1：启用、0：禁用
        /// </summary>
        public int Cstatus { get; set; }
    }
}