// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    /// <summary>
    /// 模块表单实例
    /// </summary>
    public partial class SysModuleFormInstance
    {
        /// <summary>
        /// 表单实例主键
        /// </summary>
        public string FId { get; set; }
        /// <summary>
        /// 表单主键
        /// </summary>
        public string FFormId { get; set; }
        /// <summary>
        /// 对象主键
        /// </summary>
        public string FObjectId { get; set; }
        /// <summary>
        /// 表单实例Json
        /// </summary>
        public string FInstanceJson { get; set; }
        /// <summary>
        /// 排序码
        /// </summary>
        public int? FSortCode { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? FCreatorTime { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string FCreatorUserId { get; set; }
    }
}