// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SysPrinter
    {
        public string Id { get; set; }
        public string Ip { get; set; }
        public string Printname { get; set; }
        public string Memo { get; set; }
    }
}