// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SysScaninlog
    {
        public string Id { get; set; }
        public string Groupid { get; set; }
        public int? Step { get; set; }
        public string LineId { get; set; }
        public string SiteId { get; set; }
        public string PalletCode { get; set; }
        public string Msg { get; set; }
        public string Remark { get; set; }
        public string Cdefined1 { get; set; }
        public string Cdefined2 { get; set; }
        public string Cdefined3 { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
    }
}