// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SysVersion
    {
        public decimal Seq { get; set; }
        public string Versionno { get; set; }
        public string Memo { get; set; }
        public string Url { get; set; }
    }
}