// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TbTestFloat
    {
        public string Id { get; set; }
        public double? Qty { get; set; }
        public double? Num { get; set; }
        public string Remark { get; set; }
    }
}