// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempBaseLineList
    {
        public string Id { get; set; }
        public int? ErrorFlag { get; set; }
        public string Lineid { get; set; }
    }
}