// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempTableAsnInfoT
    {
        public int? RowNum { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Itype { get; set; }
        public string Cerpcode { get; set; }
        public string Id { get; set; }
        public string Cerpcodeline { get; set; }
        public string Iquantity { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Cticketcode { get; set; }
    }
}