// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempBaseArea
    {
        public string Id { get; set; }
        public string Areaname { get; set; }
        public string Backupcpositioncode { get; set; }
        public string Backupcposition { get; set; }
        public string Flag { get; set; }
        public int? Issave { get; set; }
    }
}