// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempInassitBaseCargospace
    {
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Qty { get; set; }
        public string Caccountid { get; set; }
        public string Coperatorname { get; set; }
        public string Guid { get; set; }
        public string Casnid { get; set; }
    }
}