// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempTableTempOutbillInfoT
    {
        public int? RowNum { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cdefine1 { get; set; }
        public string Cerpcodeline { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cstatus { get; set; }
        public string Id { get; set; }
        public string Cinvbarcode { get; set; }
        public string Iqty { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Cticketcode { get; set; }
    }
}