// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class Test1
    {
        public decimal? PositionRate { get; set; }
        public decimal SpaceRate { get; set; }
        public int? Xzcount { get; set; }
        public int? Syzcount { get; set; }
        public int? Bfcount { get; set; }
        public int? Djcount { get; set; }
        public int? CzsumCount { get; set; }
        public string Cz { get; set; }
        public string Lineid { get; set; }
        public string Cranename { get; set; }
        public string Cpositioncode { get; set; }
        public decimal Totalqty { get; set; }
        public string Cinvcode { get; set; }
        public decimal Iqty { get; set; }
    }
}