// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TransactionTimeConfig
    {
        public string Id { get; set; }
        public decimal TranType { get; set; }
        public string TranErpcode { get; set; }
        public DateTime TranTime { get; set; }
        public DateTime DisableTime { get; set; }
        public string Cticketcode { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public string Typename { get; set; }
    }
}