// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TwWh01
    {
        public string Cell { get; set; }
        public int? X { get; set; }
        public int? Y { get; set; }
        public int? Z { get; set; }
        public int? L { get; set; }
        public string Id { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Imaxcapacity { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Cstatus { get; set; }
        public string Ctype { get; set; }
        public string Warehouseid { get; set; }
        public decimal? Ipriority { get; set; }
        public decimal? Ilength { get; set; }
        public decimal? Iwidth { get; set; }
        public decimal? Iheight { get; set; }
        public decimal? Ivolume { get; set; }
        public string Cusetype { get; set; }
        public string Cx { get; set; }
        public string Cy { get; set; }
        public string Cz { get; set; }
        public DateTime? Dexpiredate { get; set; }
        public string Calias { get; set; }
        public string Cerpcode { get; set; }
        public decimal? Ipermitmix { get; set; }
        public DateTime? Createtime { get; set; }
        public decimal? Ioccupyqty { get; set; }
        public decimal? IsAllo { get; set; }
        public string Lastcstatus { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public string PalletCode { get; set; }
        public string Productcode { get; set; }
        public decimal? Volume { get; set; }
        public decimal? Volumeunit { get; set; }
        public decimal? Occupyweight { get; set; }
        public decimal? Occupyvolume { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Weightunit { get; set; }
        public string Lineid { get; set; }
        public int? Islocked { get; set; }
    }
}