// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MyFileGenTool.Models
{
    public partial class V2OutbillD
    {
        public string Cticketcode { get; set; }
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public decimal Iquantity { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cerpcodeline { get; set; }
        public DateTime? Doutdate { get; set; }
        public string Coutpersoncode { get; set; }
        public string Cmemo { get; set; }
        public decimal? Ioutasnline { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public string Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public decimal? LineQty { get; set; }
        public string AllocateDIds { get; set; }
        public decimal? Allotype { get; set; }
        public string AsnDIds { get; set; }
        public decimal? PartBond { get; set; }
        public decimal? AsrsStatus { get; set; }
        public decimal? Wmstskid { get; set; }
        public decimal? AsrsNum { get; set; }
        public string PalletCode { get; set; }
        public decimal? Isgoback { get; set; }
        public string Cstoppositioncode { get; set; }
        public string Cnewpositioncode { get; set; }
        public string Callocateid { get; set; }
        public int? Lineid { get; set; }
        public int? Outasndlineid { get; set; }
        public string Wire { get; set; }
        public string Sourcecode { get; set; }
        public string Wo { get; set; }
    }
}