// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VAllocateL
    {
        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditperson { get; set; }
        public DateTime? Daudittime { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Cerpcode { get; set; }
        public string Cmemo { get; set; }
        public DateTime Dindate { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public decimal? IsAllow { get; set; }
        public decimal? Special { get; set; }
        public decimal? SpecialType { get; set; }
        public string Inasncode { get; set; }
        public string Deliveryuser { get; set; }
        public DateTime? Deliverytime { get; set; }
        public string Otype { get; set; }
        public DateTime? Debittime { get; set; }
        public string Debitowner { get; set; }
        public decimal? IsMerge { get; set; }
        public string MergeId { get; set; }
        public string MergeErp { get; set; }
        public string Lineid { get; set; }
        public decimal? CriticalPart { get; set; }
        public string Allotype { get; set; }
        public string Palletcode { get; set; }
        public string Username { get; set; }
        public string Cauditpersonname { get; set; }
        public string Cstatusname { get; set; }
    }
}