// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VAsrsList
    {
        public Guid? Id { get; set; }
        public int Wmstskid { get; set; }
        public string Cmdsno { get; set; }
        public string Cmdsts { get; set; }
        public string Prt { get; set; }
        public string Stnno { get; set; }
        public string Cmdmode { get; set; }
        public string Loc { get; set; }
        public string Newloc { get; set; }
        public string Locsize { get; set; }
        public string Rodid { get; set; }
        public string Trace { get; set; }
        public string Trndate { get; set; }
        public string Acttime { get; set; }
        public string Endtime { get; set; }
        public string Result { get; set; }
        public string Trnno { get; set; }
        public int? Billingstatus { get; set; }
        public string Createuser { get; set; }
        public string Cmdno { get; set; }
        public string Lineid { get; set; }
        public string Plcd51 { get; set; }
        public string CmdstsName { get; set; }
        public string CmdmodeName { get; set; }
        public string Ids { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cticketcode { get; set; }
        public string CaseTypeName { get; set; }
        public string CaseType { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string NewlocCode { get; set; }
        public string NewlocName { get; set; }
    }
}