// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VBarSnSplitsquery
    {
        public string Id { get; set; }
        public string SplitSn { get; set; }
        public string Cinvcode { get; set; }
        public string Cpartname { get; set; }
        public decimal SplitSnQty { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public string Cpositioncode { get; set; }
    }
}