// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VBaseBarSn
    {
        public string Id { get; set; }
        public string SnCode { get; set; }
        public string Cinvcode { get; set; }
        public string CinvcodeName { get; set; }
        public decimal? Quantity { get; set; }
        public string Cstatus { get; set; }
        public string CreateOwner { get; set; }
        public DateTime? CreateTime { get; set; }
        public string SnType { get; set; }
        public string BarType { get; set; }
        public string Vendor { get; set; }
        public string DateCode { get; set; }
    }
}