// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ViewPositionStockRatio
    {
        public string Id { get; set; }
        public string AreaName { get; set; }
        public int? PosCount { get; set; }
        public int? StockCount { get; set; }
        public int? NoStockCount { get; set; }
        public string StockRatio { get; set; }
    }
}