// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ViewGetPartNorecode
    {
        public long? Id { get; set; }
        public string Type { get; set; }
        public string Cticketcode { get; set; }
        public string Typename { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Qty { get; set; }
    }
}