// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ViewOutbillSnreport
    {
        public long? Id { get; set; }
        public string Cerpcode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Sncode { get; set; }
        public string Datecode { get; set; }
        public string Weeks { get; set; }
        public decimal? Qty { get; set; }
        public DateTime Dindate { get; set; }
        public string Cwareid { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
    }
}