// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ViewStockCheckdiff
    {
        public decimal? Isadjust { get; set; }
        public string Ddefine3 { get; set; }
        public string Cticketcode { get; set; }
        public string Ccheckname { get; set; }
        public string Cerpcode { get; set; }
        public string Cwareid { get; set; }
        public string Cwarename { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public decimal Iquantity { get; set; }
        public decimal? Onenum { get; set; }
        public DateTime? Onedate { get; set; }
        public string Onename { get; set; }
        public decimal? Twonum { get; set; }
        public DateTime? Twodate { get; set; }
        public string Twoname { get; set; }
        public decimal? Onediff { get; set; }
        public decimal? Twodiff { get; set; }
        public DateTime Dcheckdate { get; set; }
    }
}