// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOraTest
    {
        public string Itype2 { get; set; }
        public string Itype { get; set; }
        public string Erpcode { get; set; }
        public string Cticketcode { get; set; }
        public string Cpo { get; set; }
        public DateTime Dcreatetime { get; set; }
    }
}