// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOutbillReport
    {
        public string Cticketcode { get; set; }
        public string Cso { get; set; }
        public string Cwareid { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public decimal Iquantity { get; set; }
        public string Typename { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cerpcode { get; set; }
        public decimal Otype { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
        public string Cspecifications { get; set; }
    }
}