// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOutmixedJfDetialsDList
    {
        public long? Rownum { get; set; }
        public string Id { get; set; }
        public string Erpcode { get; set; }
        public decimal Otype { get; set; }
        public string Mixedcode { get; set; }
        public string Otypename { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal? Sumqty { get; set; }
        public string Cinvcode { get; set; }
    }
}