// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOutasnReport
    {
        public Guid? Id { get; set; }
        public string Cticketcode { get; set; }
        public string Cerpcode { get; set; }
        public string Cso { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Typename { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal Iquantity { get; set; }
        public decimal OutassitQty { get; set; }
        public decimal OutbillQty { get; set; }
        public decimal OutbilledQty { get; set; }
        public int Iswebcreatebill { get; set; }
        public decimal Itype { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
        public string Iswebcreatebillname { get; set; }
        public string Cspecifications { get; set; }
    }
}