// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPdaQueryOutAsnd
    {
        public string Cticketcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Inum { get; set; }
        public decimal? Yjnum { get; set; }
        public decimal? Synum { get; set; }
        public string Cmemo { get; set; }
        public string Cspecifications { get; set; }
        public decimal? WzyNum { get; set; }
    }
}