// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPdaOutMixedDlist
    {
        public string Id { get; set; }
        public string Mixedcode { get; set; }
        public string Erpcode { get; set; }
        public decimal? Otype { get; set; }
        public string Outcticketcode { get; set; }
        public string Calias { get; set; }
        public string FgCinvcode { get; set; }
        public decimal? FgQty { get; set; }
        public string FlagId { get; set; }
        public string FlagName { get; set; }
        public string Ids { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal Qty { get; set; }
        public string Remark { get; set; }
        public string Cstatus { get; set; }
        public string MixStatusName { get; set; }
        public string Agvsite { get; set; }
        public string Wo { get; set; }
        public DateTime? Creatertime { get; set; }
        public string OutmixedDCstatusName { get; set; }
        public string OutmixedDCstatus { get; set; }
        public int? Iqty { get; set; }
    }
}