// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPdaOutMixedList
    {
        public string Id { get; set; }
        public string Mixedcode { get; set; }
        public string Erpcode { get; set; }
        public decimal Otype { get; set; }
        public string Outcticketcode { get; set; }
        public string Calias { get; set; }
        public string FgCinvcode { get; set; }
        public decimal? FgQty { get; set; }
        public string FlagId { get; set; }
        public string FlagName { get; set; }
        public string Wo { get; set; }
        public DateTime? Creatertime { get; set; }
        public int? Iqty { get; set; }
    }
}