// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPdaAllocateD
    {
        public string Cinvcode { get; set; }
        public decimal Iquantity { get; set; }
        public string Cticketcode { get; set; }
        public decimal Yjnum { get; set; }
        public string Cpositioncode { get; set; }
        public string Ctopositioncode { get; set; }
        public string Cinvname { get; set; }
        public string Id { get; set; }
        public string Ids { get; set; }
        public string CriticalPart { get; set; }
        public decimal? Synum { get; set; }
    }
}