// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPdaInEmtList
    {
        public string Statusname { get; set; }
        public string Cstatus { get; set; }
        public string Cerpcodeline { get; set; }
        public int? LineId { get; set; }
        public string Ids { get; set; }
        public string Cinvcode { get; set; }
        public string Cticketcode { get; set; }
        public decimal Qty { get; set; }
        public string Userno { get; set; }
        public decimal? Iquantity { get; set; }
        public decimal? Surplusqty { get; set; }
        public string Worktype { get; set; }
        public string Cerpcode { get; set; }
    }
}