// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VStockCheckdbill
    {
        public string Cerpcode { get; set; }
        public string Cticketcode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public string Cstatus { get; set; }
        public string Statusf { get; set; }
        public string FlagName { get; set; }
        public string Checktype { get; set; }
        public string Ccheckname { get; set; }
        public string Cinvname { get; set; }
        public string Ids { get; set; }
        public decimal Qty { get; set; }
        public decimal Iquantity { get; set; }
    }
}