// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VStockDateCode
    {
        public string Ids { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Qty { get; set; }
        public string Lockuser { get; set; }
        public DateTime? Locktime { get; set; }
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cwarehouse { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Ioccupyqty { get; set; }
        public string Cdefine1 { get; set; }
        public string Cmemo { get; set; }
    }
}