// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VTempBaseVendor
    {
        public string Ids { get; set; }
        public string 供应商编码 { get; set; }
        public string 供应商名称 { get; set; }
        public string 状态 { get; set; }
        public string 联系人 { get; set; }
        public string 联系电话 { get; set; }
        public string 联系地址 { get; set; }
        public string 供应商类型 { get; set; }
        public string 助记码 { get; set; }
        public string 级别 { get; set; }
        public string 备注 { get; set; }
        public string Erp编码 { get; set; }
        public string 企业编号 { get; set; }
        public string 据点编号 { get; set; }
        public string 应用组织 { get; set; }
    }
}