// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VWarningstockReport
    {
        public string Cpartnumber { get; set; }
        public string Cpartname { get; set; }
        public decimal? Iqty { get; set; }
        public string Csafeqty { get; set; }
        public string Csafeqtyceiling { get; set; }
        public int Isalarm { get; set; }
    }
}