// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class WcsTaskProcess
    {
        public string Id { get; set; }
        public string Cticketcode { get; set; }
        public string Packageno { get; set; }
        public string Tasktype { get; set; }
        public string Cstatus { get; set; }
        public string Sourcecode { get; set; }
        public string Cdefiend1 { get; set; }
        public string Cdefiend2 { get; set; }
        public string Cdefiend3 { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
        public string Remark { get; set; }
        public DateTime? Updatedtime { get; set; }
        public int? Steps { get; set; }
    }
}