// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Inventory.Data
{
    public partial class BaseDocureason
    {
        public string Id { get; set; }
        /// <summary>
        /// 作用域 1：入库  2：出库
        /// </summary>
        public string Actionscope { get; set; }
        /// <summary>
        /// 状态码 Y:可用 N：不可用
        /// </summary>
        public string States { get; set; }
        /// <summary>
        /// 理由码编号
        /// </summary>
        public string Reasoncode { get; set; }
        /// <summary>
        /// 理由码说明
        /// </summary>
        public string Reasoncontent { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? Dcreatetime { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string Ccreateownercode { get; set; }
        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime? Lastupdatetime { get; set; }
        /// <summary>
        /// 最后更新人
        /// </summary>
        public string Lastupdateowner { get; set; }
        public string Isfromerp { get; set; }
    }
}