// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Inventory.Data
{
    public partial class FieldMapper
    {
        public string Id { get; set; }
        public string Name { get; set; }

        public int Index { get; set; } 

    }
}