// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class AllocateD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public decimal Iquantity { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public DateTime Dindate { get; set; }
        public string Cinpersoncode { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Ctopositioncode { get; set; }
        public string Ctoposition { get; set; }
        public string Cmidpositioncode { get; set; }
        public decimal? Ioriquantity { get; set; }
        public decimal? Toallocount { get; set; }
        public string OutbillDIds { get; set; }
        public string AlloType { get; set; }
        public decimal? Sptype { get; set; }
        public string Cmidpositionname { get; set; }
        public decimal? IsUpline { get; set; }
        public decimal? IsScan { get; set; }
        public decimal? PartBond { get; set; }
        public decimal? CriticalPart { get; set; }
        public decimal? AsrsStatus { get; set; }
        public decimal? Wmstskid { get; set; }
        public decimal? AsrsNum { get; set; }
        public string Lineid { get; set; }

        public virtual Allocate IdNavigation { get; set; }
    }
}