// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class AllocateLineSn
    {
        public string Id { get; set; }
        public string Erpcode { get; set; }
        public string SnCode { get; set; }
        public decimal? Datecode { get; set; }
        public string Cinvcode { get; set; }
        public decimal? SnQty { get; set; }
        public decimal? Lineqty { get; set; }
        public string LineIds { get; set; }
        public decimal? Sntype { get; set; }
        public string Createuser { get; set; }
        public DateTime? Createtime { get; set; }
        public string Lastupuser { get; set; }
        public DateTime? Lastuptime { get; set; }
    }
}