// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class AsrsShowinfo
    {
        public string Id { get; set; }
        public int? Seq { get; set; }
        public string Ctype { get; set; }
        public string Operationname { get; set; }
        public string LineId { get; set; }
        public string Siteid { get; set; }
        public string Caseid { get; set; }
        public string Casetype { get; set; }
        public string Message { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Cdefine3 { get; set; }
        public DateTime Createtime { get; set; }
        public string CreateUser { get; set; }
        public int? Isshow { get; set; }
    }
}