// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BarCartonMHis
    {
        public string Id { get; set; }
        public string CartonNo { get; set; }
        public string CartonName { get; set; }
        public string TypeId { get; set; }
        public DateTime Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastmodifytime { get; set; }
        public string Lastmodifyownere { get; set; }
    }
}