// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseOperator
    {
        public string Caccountid { get; set; }
        public string Coperatorname { get; set; }
        public string Cmemo { get; set; }
        public string Cstatus { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Calias { get; set; }
        public string Cduty { get; set; }
        public string Cdepartment { get; set; }
        public string Cphone { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Ccreateowner { get; set; }
        public string Cshift { get; set; }
        public string Cerpcode { get; set; }
        public string Id { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
    }
}