// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseTypeMapping
    {
        public string Id { get; set; }
        public string WmsTypeCode { get; set; }
        public string WmsTypeName { get; set; }
        public string ErpTypeCode { get; set; }
        public string ErpTypeName { get; set; }
        public string Type { get; set; }
        public string Cstatus { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Dcreateuser { get; set; }
    }
}