// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseBarSn
    {
        public string Id { get; set; }
        public string SnCode { get; set; }
        public string Datecode { get; set; }
        public string Bonded { get; set; }
        public decimal? Validitydate { get; set; }
        public string Vendor { get; set; }
        public string VendorName { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Cinvcode { get; set; }
        public string CinvcodeName { get; set; }
        public decimal? Quantity { get; set; }
        public string SnType { get; set; }
        public DateTime? CreateTime { get; set; }
        public string CreateOwner { get; set; }
        public DateTime? LastUpdTime { get; set; }
        public string LastUpdOwner { get; set; }
        public string Cpositioncode { get; set; }
        public string PoNumber { get; set; }
        public string BatchNumber { get; set; }
        public decimal? BatchQty { get; set; }
        public string BarType { get; set; }
        public decimal? BoxNum { get; set; }
        public string BarCodeType { get; set; }
        public string PoLineId { get; set; }
        public string SoNumber { get; set; }
        public string SoLineId { get; set; }
        public string ClientCode { get; set; }
        public string ClinetName { get; set; }
        public string ArbitraryVal1 { get; set; }
        public string ArbitraryVal2 { get; set; }
        public string ArbitraryVal3 { get; set; }
        public string ArbitraryVal4 { get; set; }
        public string ArbitraryVal5 { get; set; }
        public string ArbitraryVal6 { get; set; }
        public string ArbitraryVal7 { get; set; }
        public string ArbitraryVal8 { get; set; }
        public string ArbitraryVal9 { get; set; }
        public string ArbitraryVal10 { get; set; }
        public string CodeRuleId { get; set; }
        public string PrintRuleId { get; set; }
        public string PrintVal1 { get; set; }
        public string PrintVal2 { get; set; }
        public string PrintVal3 { get; set; }
        public string PrintVal4 { get; set; }
        public string PrintVal5 { get; set; }
        public string PrintVal6 { get; set; }
        public string PrintVal7 { get; set; }
        public string PrintVal8 { get; set; }
        public string PrintVal9 { get; set; }
        public string PrintVal10 { get; set; }
    }
}