// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BasePartCargospace
    {
        public string Cpartnumber { get; set; }
        public string Cwareid { get; set; }
        public string Cpositioncode { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Cdatetime { get; set; }
        public string Id { get; set; }
    }
}