// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseOfCc
    {
        public string Item1 { get; set; }
        public string Cw { get; set; }
        public string Item2 { get; set; }
        public string Qk { get; set; }
    }
}