// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseCargospaceTemp
    {
        public string Id { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Imaxcapacity { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Ddefine3 { get; set; }
        public string Ddefine4 { get; set; }
        public string Idefine5 { get; set; }
        public string Cstatus { get; set; }
        public string Ctype { get; set; }
        public string Warehouseid { get; set; }
        public string Ipriority { get; set; }
        public string Ilength { get; set; }
        public string Iwidth { get; set; }
        public string Iheight { get; set; }
        public string Ivolume { get; set; }
        public string Cusetype { get; set; }
        public string Cx { get; set; }
        public string Cy { get; set; }
        public string Cz { get; set; }
        public string Dexpiredate { get; set; }
        public string Calias { get; set; }
        public string Cerpcode { get; set; }
        public string Ipermitmix { get; set; }
        public string Createtime { get; set; }
        public string Ioccupyqty { get; set; }
        public string IsAllo { get; set; }
        public string Lastcstatus { get; set; }
        public string Weight { get; set; }
        public string Weightunit { get; set; }
        public string Volume { get; set; }
        public string Volumeunit { get; set; }
        public string Flag { get; set; }
        public string Createowner { get; set; }
        public string Lineid { get; set; }
        public string PalletCode { get; set; }
    }
}