// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseDeliverDepartment
    {
        public string Id { get; set; }
        public string Operatorno { get; set; }
        public string Departmentno { get; set; }
        public string Departmentname { get; set; }
        public DateTime? Createdate { get; set; }
        public string Createuser { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateuser { get; set; }
    }
}