// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BasePlcCurrentStatus
    {
        public string Id { get; set; }
        public string LineId { get; set; }
        public string Status { get; set; }
        public DateTime? CreateTime { get; set; }
        public string CreateUser { get; set; }
        public string Remark { get; set; }
    }
}