// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class BaseBarcodeRuleD
    {
        public string Id { get; set; }
        /// <summary>
        /// 主表ID
        /// </summary>
        public string Ruleid { get; set; }
        /// <summary>
        /// 项次
        /// </summary>
        public int? Sno { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 长度
        /// </summary>
        public int? Ilength { get; set; }
        /// <summary>
        /// 开始位置
        /// </summary>
        public int? Ifrom { get; set; }
        /// <summary>
        /// 结束位置
        /// </summary>
        public int? Ito { get; set; }
        /// <summary>
        /// 类型
        /// </summary>
        public string Barcodetypeid { get; set; }
        /// <summary>
        /// 格式
        /// </summary>
        public string Formatid { get; set; }
        /// <summary>
        /// 默认值
        /// </summary>
        public string Defaultvalue { get; set; }
        /// <summary>
        /// 必填项
        /// </summary>
        public string Mandatory { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string Createuser { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? Createdate { get; set; }
        /// <summary>
        /// 最后修改人
        /// </summary>
        public string Modifyuser { get; set; }
        /// <summary>
        /// 最后修改时间
        /// </summary>
        public DateTime? Modifydate { get; set; }
    }
}