// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class Checkerrormsg
    {
        public string Errormsg { get; set; }
        public string Userno { get; set; }
        public string Guid { get; set; }
        public DateTime? Createdate { get; set; }
    }
}