// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class CmdAgvpositionCodeDetail
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// AGV任务单编号
        /// </summary>
        public string Taskid { get; set; }
        /// <summary>
        /// 位置类型 00 表示：位置编号 01 表示：物料批次号 02 表示：策略编号（含多个区域） 如：第一个区域放不下, 可以放第二个区域 03 表示：货架编号，通过货架编号找到货架所在位置 04 表示：区域编号，在区域中查找可用位置
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// 位置路径：AGV 关键路径位置集合，与任务类型中模板配置的位置路径一一对应。待现场地图部署、配置完成后可获取；
        /// </summary>
        public string Positioncodepath { get; set; }
        /// <summary>
        /// 位置路径顺序，任务模板中如果2个位置点，将根据任务点的先后顺序默认为起点和终点。相同任务单顺序号不可重复。1开始 2结束
        /// </summary>
        public int Codepathorder { get; set; }
        /// <summary>
        /// 任务生成者
        /// </summary>
        public string CreateOwner { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime Createtime { get; set; }
    }
}