// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class CmdMstError
    {
        public string Id { get; set; }
        public string Lineid { get; set; }
        public string Errorindex { get; set; }
        public string Errorcode { get; set; }
        public string Errormsg { get; set; }
        public DateTime Createtime { get; set; }
        public string Hexerrorcode { get; set; }
    }
}