// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class CmdMst
    {
        /// <summary>
        /// 主键
        /// </summary>
        public int WmsTskId { get; set; }
        /// <summary>
        /// 命令序号 00001~24999
        /// </summary>
        public string CmdSno { get; set; }
        /// <summary>
        /// 命令状态 0:未处理 1:执行中 7:命令完成待过账
        /// </summary>
        public string CmdSts { get; set; }
        /// <summary>
        /// 优先顺位 1~9 (1最优先)
        /// </summary>
        public string Prt { get; set; }
        /// <summary>
        /// 站别 101:Crane1第1站(左边)  201:Crane2第2站(右边)
        /// </summary>
        public string StnNo { get; set; }
        /// <summary>
        /// 命令模式 1:入库 2:出库 3:盘点 5:库对库
        /// </summary>
        public string CmdMode { get; set; }
        /// <summary>
        /// 命令存取储位: RRBBBLLL。 R:列(Row)，两码。B:格(Bay)，三码。L:层(Level)，两码。
        /// </summary>
        public string Loc { get; set; }
        /// <summary>
        /// 目的储位 (库对库命令使用): RRBBBLL。 R:列(Row)，两码。B:格(Bay)，三码。L:层(Level)，两码。
        /// </summary>
        public string NewLoc { get; set; }
        /// <summary>
        /// 储位种类 1:小储位  2:大储位
        /// </summary>
        public string LocSize { get; set; }
        /// <summary>
        /// 盘元ID
        /// </summary>
        public string RodId { get; set; }
        /// <summary>
        /// 命令执行进程
        /// </summary>
        public string Trace { get; set; }
        /// <summary>
        /// 命令产生时间
        /// </summary>
        public string TrnDate { get; set; }
        /// <summary>
        /// 命令送出时间
        /// </summary>
        public string ActTime { get; set; }
        /// <summary>
        /// 命令完成时间
        /// </summary>
        public string EndTime { get; set; }
        /// <summary>
        /// 命令结束结果 参考Result表,wcs自用
        /// </summary>
        public string Result { get; set; }
        /// <summary>
        /// WMS自定义
        /// </summary>
        public string TrnNo { get; set; }
        /// <summary>
        /// 单据状态 判断订单（入库单\出库单\调拨单）是否扣账
        /// </summary>
        public int? Billingstatus { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string Createuser { get; set; }
        public int? Updata { get; set; }
        /// <summary>
        /// 多条线的线别
        /// </summary>
        public string Cmdno { get; set; }
        /// <summary>
        /// 多条线的线别
        /// </summary>
        public string Lineid { get; set; }
        /// <summary>
        /// 入库单\出库单\调拨单
        /// </summary>
        public string Cticketcode { get; set; }
        /// <summary>
        /// 箱号
        /// </summary>
        public string Packageno { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// D51地址
        /// </summary>
        public string Plcd51 { get; set; }
        public string BillingNo { get; set; }
        public string Msg { get; set; }
        public string TaskNo { get; set; }
        public string SourceWmsTskId { get; set; }
        public string IsPause { get; set; }
        public string SendApi { get; set; }
        public string Apistatus { get; set; }
        public string Jhsite { get; set; }
    }
}