// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class Inassit
    {
        public Inassit()
        {
            InassitD = new HashSet<InassitD>();
        }

        public string Ccreateownercode { get; set; }
        public DateTime? Dcreatetime { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Casnid { get; set; }
        public string Cmemo { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Cdefine3 { get; set; }
        public DateTime? Cdefine4 { get; set; }
        public decimal? Cdefine5 { get; set; }
        public string Id { get; set; }
        public decimal? CriticalPart { get; set; }

        public virtual ICollection<InassitD> InassitD { get; set; }
    }
}