// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class LogOutsnTest
    {
        public string Id { get; set; }
        public string Qty { get; set; }
        public string StockId { get; set; }
        public string Sncode { get; set; }
        public string Datecode { get; set; }
        public string Furnaceno { get; set; }
        public string Stocktype { get; set; }
        public DateTime? Idate { get; set; }
    }
}