// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class LogRevokeTempinbill
    {
        public string Id { get; set; }
        public string Palletdcode { get; set; }
        public string Inbillcode { get; set; }
        public string Cticketcode { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorMsg { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}