// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class LogSyserror
    {
        public string Id { get; set; }
        public string SovrceNo { get; set; }
        public string Errormsg { get; set; }
        /// <summary>
        /// 0 : 系统日志 ，1: 上架指引，2: 拣货指引, 3 ：入库扣帐, 4：出库扣帐
        /// </summary>
        public decimal Type { get; set; }
        public DateTime Createdate { get; set; }
        public int? Errorcode { get; set; }
    }
}