// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class MlogStockCurrent
    {
        public string Id { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Iqty { get; set; }
        public decimal? Ioccupyqty { get; set; }
        public string MRow { get; set; }
        public decimal? Sequence { get; set; }
        public DateTime? Snaptime { get; set; }
        public string Dmltype { get; set; }
        public string OldNew { get; set; }
        public byte[] ChangeVector { get; set; }
        public decimal? Xid { get; set; }
    }
}