// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class OutasnDSplit
    {
        public string Id { get; set; }
        public string OutasnId { get; set; }
        public string OutasnDIds { get; set; }
        public string CinvCode { get; set; }
        public string Flag { get; set; }
        public decimal? OldQty { get; set; }
        public decimal? CjQty { get; set; }
        public DateTime? CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}