// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class R09WhZ
    {
        public string L { get; set; }
        public int? Z { get; set; }
        public int? CntY { get; set; }
        public int? CntCell { get; set; }
    }
}