// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ReportPartMoreSpace
    {
        public string Id { get; set; }
        public string Warehouse { get; set; }
        public string Cpositioncode { get; set; }
        public string Cpositionname { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iqty { get; set; }
        public decimal? Remainspace { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createuser { get; set; }
    }
}