// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SalesOrderD
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string PartNo { get; set; }
        public decimal ShipQty { get; set; }
        public decimal Price { get; set; }
        public DateTime RequestShipDate { get; set; }
        public string CreateOwer { get; set; }
        public DateTime CreateTime { get; set; }
        public string LastUpdOwner { get; set; }
        public DateTime? LastUpdTime { get; set; }

        public virtual SalesOrderM IdNavigation { get; set; }
    }
}