// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class StockRecheckSn
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// SN
        /// </summary>
        public string Sn { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public decimal? Qty { get; set; }
        /// <summary>
        /// 物料编码
        /// </summary>
        public string Cinvcode { get; set; }
        /// <summary>
        /// 物料名称
        /// </summary>
        public string Cinvname { get; set; }
        /// <summary>
        /// 储位编码
        /// </summary>
        public string Cpositioncode { get; set; }
        /// <summary>
        /// 储位名称
        /// </summary>
        public string Cpositionname { get; set; }
        /// <summary>
        /// 重验次数
        /// </summary>
        public int? Checknum { get; set; }
        /// <summary>
        /// 重验1天数
        /// </summary>
        public int? Checkdays1 { get; set; }
        /// <summary>
        /// 重验1结果
        /// </summary>
        public int? Checkdays1result { get; set; }
        /// <summary>
        /// 重验1的人员
        /// </summary>
        public string Checkdays1user { get; set; }
        /// <summary>
        /// 重验1的日期
        /// </summary>
        public DateTime? Checkdays1date { get; set; }
        /// <summary>
        /// 自定义1
        /// </summary>
        public string Cdefind1 { get; set; }
        /// <summary>
        /// 自定义2
        /// </summary>
        public string Cdefind2 { get; set; }
        /// <summary>
        /// 自定义3
        /// </summary>
        public string Cdefind3 { get; set; }
        /// <summary>
        /// 自定义4
        /// </summary>
        public string Cdefind4 { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Cmemo { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string Ccreateownercode { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? Dcreatetime { get; set; }
        /// <summary>
        /// 最后修改人
        /// </summary>
        public string Clastupdatedownercode { get; set; }
        /// <summary>
        /// 最后修改日期
        /// </summary>
        public DateTime? Dlastupdatedtime { get; set; }
    }
}