// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class StockTemp
    {
        public string Cinvcode { get; set; }
        public string Cpositioncode { get; set; }
        public decimal Quantity { get; set; }
        public string Palletcode { get; set; }
        public int? Status { get; set; }
        public string Id { get; set; }
    }
}