// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class StockCurrentPalletCode
    {
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string CinvName { get; set; }
        public decimal? IQuantity { get; set; }
        public string PalletCode { get; set; }
        public int? IType { get; set; }
        public string AgvsiteCode { get; set; }
        public string AgvsiteName { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? DCreateDate { get; set; }
        public string DCreateOwner { get; set; }
    }
}