// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class SysLogType
    {
        public string Id { get; set; }
        public string GroupName { get; set; }
        public string TypeId { get; set; }
        public string TypeName { get; set; }
        public string Remark { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}