// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    /// <summary>
    /// 角色表
    /// </summary>
    public partial class SysRole
    {
        /// <summary>
        /// 角色主键
        /// </summary>
        public string FId { get; set; }
        /// <summary>
        /// 组织主键
        /// </summary>
        public string FOrganizeId { get; set; }
        /// <summary>
        /// 分类:1-角色2-岗位
        /// </summary>
        public int? FCategory { get; set; }
        /// <summary>
        /// 编号
        /// </summary>
        public string FEnCode { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string FFullName { get; set; }
        /// <summary>
        /// 类型
        /// </summary>
        public string FType { get; set; }
        /// <summary>
        /// 允许编辑
        /// </summary>
        public bool? FAllowEdit { get; set; }
        /// <summary>
        /// 允许删除
        /// </summary>
        public bool? FAllowDelete { get; set; }
        /// <summary>
        /// 排序码
        /// </summary>
        public int? FSortCode { get; set; }
        /// <summary>
        /// 删除标志
        /// </summary>
        public bool? FDeleteMark { get; set; }
        /// <summary>
        /// 有效标志
        /// </summary>
        public bool? FEnabledMark { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string FDescription { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? FCreatorTime { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string FCreatorUserId { get; set; }
        /// <summary>
        /// 最后修改时间
        /// </summary>
        public DateTime? FLastModifyTime { get; set; }
        /// <summary>
        /// 最后修改用户
        /// </summary>
        public string FLastModifyUserId { get; set; }
        /// <summary>
        /// 删除时间
        /// </summary>
        public DateTime? FDeleteTime { get; set; }
        /// <summary>
        /// 删除用户
        /// </summary>
        public string FDeleteUserId { get; set; }
    }
}