// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempQueryInOutdetailsReport
    {
        public string Id { get; set; }
        public string CreateDate { get; set; }
        public string Cticketcode { get; set; }
        public string Cinvcode { get; set; }
        public string Typename { get; set; }
        public string Erpcode { get; set; }
        public decimal? Insummary { get; set; }
        public decimal? Outsummary { get; set; }
        public decimal? Stocksummary { get; set; }
        public string Ymonth { get; set; }
    }
}