// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempTvshowInfo
    {
        public string Id { get; set; }
        public string LineName { get; set; }
        public string SiteName { get; set; }
        public string PallatCodeCount { get; set; }
        public string Erpcode { get; set; }
        public string OutBillCode { get; set; }
        public string PositionCodeOut { get; set; }
        public string PallatCode { get; set; }
        public string Wl1Out { get; set; }
        public decimal? OutBillQty1 { get; set; }
        public decimal? OutJhqty1 { get; set; }
        public decimal? OutFkqty1 { get; set; }
        public string Wl2Out { get; set; }
        public decimal? OutBillQty2 { get; set; }
        public decimal? OutJhqty2 { get; set; }
        public decimal? OutFkqty2 { get; set; }
        public string Wl3Out { get; set; }
        public decimal? OutBillQty3 { get; set; }
        public decimal? OutJhqty3 { get; set; }
        public decimal? OutFkqty3 { get; set; }
        public string Wl4Out { get; set; }
        public decimal? OutBillQty4 { get; set; }
        public decimal? OutJhqty4 { get; set; }
        public decimal? OutFkqty4 { get; set; }
        public string OutFb { get; set; }
        public string Message { get; set; }
        public string StatusOut { get; set; }
        public DateTime? CreateTime { get; set; }
    }
}