// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempBinCard
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Binuserno { get; set; }
        public DateTime? Tradtime { get; set; }
        public string Cinvcode { get; set; }
        public string Cwarename { get; set; }
        public string Cpositioncode { get; set; }
        public string Erpcode { get; set; }
        public string Typecode { get; set; }
        public string Outintype { get; set; }
        public string Managers { get; set; }
        public decimal? Inqty { get; set; }
        public decimal? Outqty { get; set; }
        public decimal? Balancenum { get; set; }
        public string Cticketcode { get; set; }
        public string Memo { get; set; }
        public string Iotype { get; set; }
    }
}