// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempOutbilltotalqty
    {
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Totalqty { get; set; }
        public string Coutasnid { get; set; }
        public string Userno { get; set; }
        public string Guid { get; set; }
    }
}