// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TempTableInfoT
    {
        public int? RowNum { get; set; }
        public string Cpositioncode { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Cticketcode { get; set; }
    }
}