// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class TwWh02
    {
        public int? L { get; set; }
        public int? Z { get; set; }
        public int? Y { get; set; }
        public int? X { get; set; }
        public string Cell { get; set; }
        public string P { get; set; }
        public decimal? Qty { get; set; }
        public string Dt { get; set; }
        public string Hr { get; set; }
    }
}