// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VAllocateDreport
    {
        public long? Rum { get; set; }
        public string Cticketcode { get; set; }
        public string Cerpcode { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal Iquantity { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Ctopositioncode { get; set; }
        public string Ctoposition { get; set; }
        public string Cinpersoncode { get; set; }
        public DateTime Dindate { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditperson { get; set; }
        public DateTime? Daudittime { get; set; }
        public string Cstatus { get; set; }
        public string Allotype { get; set; }
        public string WorkTypeName { get; set; }
        public string Cspecifications { get; set; }
    }
}