// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VBaseArea
    {
        public string Id { get; set; }
        public string AreaName { get; set; }
        public string HandoverCargo { get; set; }
        public string HandoverCargoName { get; set; }
        public string Flag { get; set; }
        public string Memo { get; set; }
        public string Createowner { get; set; }
        public DateTime? Createtime { get; set; }
        public string IsControlNew { get; set; }
        public string IsControl { get; set; }
    }
}