// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VChayireport
    {
        public string Cticketcode { get; set; }
        public string Ccheckname { get; set; }
        public string Checkcode { get; set; }
        public string Cerpcode { get; set; }
        public string Checktype { get; set; }
        public string Cwareid { get; set; }
        public string Cwarename { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Iqt { get; set; }
        public string Cdefine2 { get; set; }
        public decimal? Iqtnow0 { get; set; }
        public decimal? Iqtnow1 { get; set; }
        public DateTime? Actualtime0 { get; set; }
        public DateTime? Actualtime1 { get; set; }
        public decimal? Diffcount0 { get; set; }
        public decimal? Diffcount1 { get; set; }
        public string Ccheckpersoncode { get; set; }
        public string Dcheckdate { get; set; }
        public string Worktype { get; set; }
        public string WorkTypeName { get; set; }
        public string Cspecifications { get; set; }
    }
}