// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VCmdMst
    {
        public string Packageno { get; set; }
        public string Remark { get; set; }
        public string CmdSts { get; set; }
        public string LineId { get; set; }
        public string StnNo { get; set; }
        public string Loc { get; set; }
        public string TrnDate { get; set; }
        public string ActTime { get; set; }
        public string EndTime { get; set; }
        public string Cticketcode { get; set; }
        public string Result { get; set; }
        public int WmsTskId { get; set; }
        public string Prt { get; set; }
        public string NewLoc { get; set; }
        public string CmdMode { get; set; }
        public string CmdSno { get; set; }
        public string TaskNo { get; set; }
        public string Msg { get; set; }
    }
}