// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VEbsTranTest
    {
        public decimal TransactionId { get; set; }
        public string Item { get; set; }
        public string SubinventoryCode { get; set; }
        public string Locator { get; set; }
        public string TransactionSourceName { get; set; }
        public string TransactionTypeName { get; set; }
        public string TransactionActionName { get; set; }
        public decimal? TransactionSourceId { get; set; }
        public string TransactionReference { get; set; }
        public string SourceCode { get; set; }
        public string WmsUser { get; set; }
        public string WmsNum { get; set; }
        public decimal? TrxSourceLineId { get; set; }
        public decimal? DsNum { get; set; }
        public string ReceiptNum { get; set; }
        public string TransferSubinventory { get; set; }
        public string TransferLocator { get; set; }
        public string SourceName { get; set; }
        public decimal TransactionQuantity { get; set; }
        public DateTime TransactionDate { get; set; }
    }
}