// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ViewPositionNostocklistLine
    {
        public Guid? Id { get; set; }
        public string Line { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
    }
}