// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class ViewGetCargoRma
    {
        public string Cpositioncode { get; set; }
        public string Cpositionname { get; set; }
    }
}