// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VInAsnEmt
    {
        public string Ids { get; set; }
        public string Cinvbarcode { get; set; }
        public string PalletCode { get; set; }
        public string Id { get; set; }
        public string Cerpcode { get; set; }
        public string Itype { get; set; }
        public string Cerpcodeline { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cstatus { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public string Cticketcode { get; set; }
        public string Worktype { get; set; }
        public string WorktypeName { get; set; }
    }
}