// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VInAsnPo
    {
        public string Cerpcode { get; set; }
        public string LineNum { get; set; }
        public decimal? ReceiptLineNum { get; set; }
        public string Cpartnumber { get; set; }
        public string Cpartname { get; set; }
        public string Segment1 { get; set; }
        public decimal? Qty { get; set; }
    }
}