// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VInasnsplit
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cinvbarcode { get; set; }
        public string Cbatch { get; set; }
        public string Cerpcodeline { get; set; }
        public string PoNumbername { get; set; }
        public string PoLinenumbername { get; set; }
        public string Mstatus { get; set; }
        public decimal? InBillQty { get; set; }
        public decimal? InBilledQty { get; set; }
        public decimal? LessQty { get; set; }
    }
}