// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VInMergePallete
    {
        public string Palletcode { get; set; }
        public string SnCode { get; set; }
        public string Cstatus { get; set; }
        public string Cerpcode { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public DateTime? Createtime { get; set; }
        public string Cticketcode { get; set; }
        public string Inasnid { get; set; }
        public string Inasncode { get; set; }
        public string Id { get; set; }
        public string OutasncodePallet { get; set; }
        public string OutbillcodePallet { get; set; }
        public string InasncodePallet { get; set; }
        public string InbillcodePallet { get; set; }
        public string Createuser { get; set; }
    }
}