// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VInpo
    {
        public string Id { get; set; }
        public string Ids { get; set; }
        public string Vendorid { get; set; }
        public string Vendorname { get; set; }
        public string Pono { get; set; }
        public DateTime? Podate { get; set; }
        public string Potype { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public decimal? Iquantity { get; set; }
    }
}