// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VMergeErpCodeReport
    {
        public long? RowNum { get; set; }
        public string Cerpcode { get; set; }
        public string Mergecode { get; set; }
        public string Ultracode { get; set; }
        public string Psongcode { get; set; }
        public string Smtcode { get; set; }
        public string Nosmtcode { get; set; }
        public string Callback { get; set; }
    }
}