// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VMixedIngredients
    {
        public string Erpcode { get; set; }
        public decimal Otype { get; set; }
        public string Otypename { get; set; }
        public decimal Sumqty { get; set; }
        public decimal Ymixedqty { get; set; }
        public decimal? Wmixedqty { get; set; }
        public decimal Kmixedqty { get; set; }
    }
}