// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VNotusePositioncode
    {
        public string PositionCode { get; set; }
        public string Cticketcode { get; set; }
    }
}