// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOutAsnAdj
    {
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditpersoncode { get; set; }
        public DateTime? Dauditdate { get; set; }
        public string Cticketcode { get; set; }
        public string Cstatus { get; set; }
        public string Cerpcode { get; set; }
        public string Cso { get; set; }
        public string Id { get; set; }
    }
}