// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOutasnDl1
    {
        public string Id { get; set; }
        public string Cso { get; set; }
        public decimal? Isoline { get; set; }
        public string Cinvname { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvbarcode { get; set; }
        public decimal Iquantity { get; set; }
        public string Cstatus { get; set; }
        public string Cbatch { get; set; }
        public string Cerpcodeline { get; set; }
        public string Ids { get; set; }
        public string Mstatus { get; set; }
        public decimal? OutBillQty { get; set; }
        public decimal? OutBilledQty { get; set; }
        public int? Lineid { get; set; }
        public string Cspecifications { get; set; }
    }
}