// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VOutbill
    {
        public string Id { get; set; }
        public string Ccreateownercode { get; set; }
        public DateTime Dcreatetime { get; set; }
        public string Cauditperson { get; set; }
        public DateTime? Daudittime { get; set; }
        public string Cclientcode { get; set; }
        public string Cclient { get; set; }
        public string Cticketcode { get; set; }
        public string Cerpcode { get; set; }
        public string Coutasnid { get; set; }
        public string Cmemo { get; set; }
        public DateTime Dindate { get; set; }
        public string Cso { get; set; }
        public string Bccode { get; set; }
        public decimal Otype { get; set; }
        public string Typename { get; set; }
        public string Cstatus { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Debittime { get; set; }
        public string Debitowner { get; set; }
        public string SnCode { get; set; }
        public int? Operationtype { get; set; }
        public string Worktype { get; set; }
        public string CstatusName { get; set; }
    }
}