// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPdaAllocateEditShow
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cpositioncode { get; set; }
        public string Ctopositioncode { get; set; }
        public decimal Iquantity { get; set; }
        public string Cticketcode { get; set; }
        public decimal Yjsl { get; set; }
        public decimal? Synum { get; set; }
    }
}