// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VPlcCmdMst
    {
        public string Id { get; set; }
        public string LineId { get; set; }
        public string CmdSno { get; set; }
        public string CmdMode { get; set; }
        public string SiteNo { get; set; }
        public string PositionCode { get; set; }
        public string TopositionCode { get; set; }
        public string Result { get; set; }
        public string CompleteIndex { get; set; }
        public string Runposition { get; set; }
        public string Sjjposition { get; set; }
        public string Difftimes { get; set; }
        public string RunTime { get; set; }
        public DateTime? Createtime { get; set; }
        public string Remark { get; set; }
    }
}