// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VRationalIssue
    {
        public string Cerpcodeline { get; set; }
        public string Cinvcode { get; set; }
        public decimal Iquantity { get; set; }
        public decimal Inum { get; set; }
        public decimal Tiquantity { get; set; }
        public decimal Odiquantity { get; set; }
        public decimal Oqty { get; set; }
        public double? Inum1 { get; set; }
    }
}