// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VStockPostiton
    {
        public string Id { get; set; }
        public string Wareid { get; set; }
        public string Cwareid { get; set; }
        public string Cwarename { get; set; }
        public string Ctype { get; set; }
        public string Ctyename { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Usage { get; set; }
        public string Palletcode { get; set; }
        public string Usagename { get; set; }
        public string HasPallet { get; set; }
        public string HasPalletname { get; set; }
    }
}