// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VStockDataCodeEdit
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public decimal? Datecode { get; set; }
        public decimal? Qty { get; set; }
        public string Lockqty { get; set; }
        public decimal? Ioccupyqty { get; set; }
    }
}