// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VStockCurrentList
    {
        public string Ids { get; set; }
        public string Id { get; set; }
        public string Cwarename { get; set; }
        public string Cwarehousecode { get; set; }
        public string Cwarehouse { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cdatecode { get; set; }
        public decimal Iqty { get; set; }
        public decimal? Ioccupyqty { get; set; }
        public decimal? Locknum { get; set; }
        public string Cerpcode { get; set; }
        public string PalletCode { get; set; }
        public string Calias { get; set; }
        public string Palletcode1 { get; set; }
        public string Cspecifications { get; set; }
    }
}