// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VTempBaseClient
    {
        public string Id { get; set; }
        public string 客户编码 { get; set; }
        public string 客户名称 { get; set; }
        public string 状态 { get; set; }
        public string 联系人 { get; set; }
        public string 联系电话 { get; set; }
        public string 联系地址 { get; set; }
        public string 客户类型 { get; set; }
        public string 助记码 { get; set; }
        public string 级别 { get; set; }
        public string 备注 { get; set; }
        public string Erp编码 { get; set; }
    }
}