// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class VTempBaseStockCurrent
    {
        public string Id { get; set; }
        public string 仓库编码 { get; set; }
        public string 储位编码 { get; set; }
        public string 物料编码 { get; set; }
        public string 数量 { get; set; }
    }
}