// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace T0002.Models
{
    public partial class WarnTempStockInfo
    {
        public string Id { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Datecode { get; set; }
        public string Cpositioncode { get; set; }
        public string Cposition { get; set; }
        public string Cwarecode { get; set; }
        public string Cwarename { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Cshelflife { get; set; }
        public decimal? Dayspast { get; set; }
        public DateTime? Senddate { get; set; }
        public string Cargocode { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public string Cdefine3 { get; set; }
        public string Createuser { get; set; }
        public DateTime? Createdate { get; set; }
    }
}